// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Carwash_UI_LCD

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_welcomepage_screen_init();
    ui_AdminPanel_screen_init();
    ui_SelectPaymentpage_screen_init();
    ui_CoinPaymentpage_screen_init();
    ui_GcashPaymentScreen_screen_init();
    ui_GcashQRsc_screen_init();
    ui_MainScreen_screen_init();
    ui_thankyouscreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_welcomepage);
}

void ui_destroy(void)
{
    ui_welcomepage_screen_destroy();
    ui_AdminPanel_screen_destroy();
    ui_SelectPaymentpage_screen_destroy();
    ui_CoinPaymentpage_screen_destroy();
    ui_GcashPaymentScreen_screen_destroy();
    ui_GcashQRsc_screen_destroy();
    ui_MainScreen_screen_destroy();
    ui_thankyouscreen_screen_destroy();
}
