// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Carwash_UI_LCD

#ifndef _CARWASH_UI_LCD_UI_H
#define _CARWASH_UI_LCD_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_welcomepage.h"
#include "ui_AdminPanel.h"
#include "ui_SelectPaymentpage.h"
#include "ui_CoinPaymentpage.h"
#include "ui_GcashPaymentScreen.h"
#include "ui_GcashQRsc.h"
#include "ui_MainScreen.h"
#include "ui_thankyouscreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_logo_png);    // assets/logo.png
LV_IMG_DECLARE(ui_img_346396786);    // assets/a227420d78aa5a2aaae939715e9ce864-removebg-preview-removebg-preview.png
LV_IMG_DECLARE(ui_img_1834858727);    // assets/890893-200.png
LV_IMG_DECLARE(ui_img_water_png);    // assets/water.png
LV_IMG_DECLARE(ui_img_2086251881);    // assets/Screenshot_2026-07-14_140943-removebg-preview.png
LV_IMG_DECLARE(ui_img_246023399);    // assets/Screenshot_2026-07-14_141214-removebg-preview.png
LV_IMG_DECLARE(ui_img_1364712669);    // assets/Screenshot_2026-07-14_141234-removebg-preview.png
LV_IMG_DECLARE(ui_img_898050187);    // assets/pngtree-thank-you-text-lettering-png-image_291020.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
