// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Carwash_UI_LCD

#ifndef UI_ADMINPANEL_H
#define UI_ADMINPANEL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AdminPanel
extern void ui_AdminPanel_screen_init(void);
extern void ui_AdminPanel_screen_destroy(void);
extern lv_obj_t * ui_AdminPanel;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_WaterCon;
extern lv_obj_t * ui_lblPressure;
extern void ui_event_swPressure(lv_event_t * e);
extern lv_obj_t * ui_swPressure;
extern lv_obj_t * ui_PressureStat;
extern lv_obj_t * ui_FaucetCon;
extern lv_obj_t * ui_lblFaucet;
extern void ui_event_swfaucet(lv_event_t * e);
extern lv_obj_t * ui_swfaucet;
extern lv_obj_t * ui_FaucetStat;
extern lv_obj_t * ui_BlowerCon;
extern lv_obj_t * ui_lblBlower;
extern void ui_event_swBlower(lv_event_t * e);
extern lv_obj_t * ui_swBlower;
extern lv_obj_t * ui_BlowerStat;
extern lv_obj_t * ui_SoapCon;
extern lv_obj_t * ui_lblsoap;
extern void ui_event_swSoap(lv_event_t * e);
extern lv_obj_t * ui_swSoap;
extern lv_obj_t * ui_SoapStat;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_cpanelwaterquallbl;
extern lv_obj_t * ui_cpanelwaterqualstat;
extern lv_obj_t * ui_cpanelwifilbl;
extern lv_obj_t * ui_cpanelwifistat;
extern lv_obj_t * ui_cpanelcoinacclbl;
extern lv_obj_t * ui_cpanelcoinaccstat;
extern lv_obj_t * ui_cpanelwqstate;
extern lv_obj_t * ui_cpanelwifistate;
extern lv_obj_t * ui_cpanelccstate;
extern void ui_event_backbtn3(lv_event_t * e);
extern lv_obj_t * ui_backbtn3;
extern lv_obj_t * ui_backlbl3;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern void ui_event_testwater(lv_event_t * e);
extern lv_obj_t * ui_testwater;
extern lv_obj_t * ui_Label14;
extern void ui_event_testsoap(lv_event_t * e);
extern lv_obj_t * ui_testsoap;
extern lv_obj_t * ui_Label16;
extern void ui_event_testblower(lv_event_t * e);
extern lv_obj_t * ui_testblower;
extern lv_obj_t * ui_Label17;
extern void ui_event_testfaucet(lv_event_t * e);
extern lv_obj_t * ui_testfaucet;
extern lv_obj_t * ui_Label18;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

