// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Carwash_UI_LCD

#include "ui.h"

lv_obj_t * ui_AdminPanel = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_WaterCon = NULL;
lv_obj_t * ui_lblPressure = NULL;
lv_obj_t * ui_swPressure = NULL;
lv_obj_t * ui_PressureStat = NULL;
lv_obj_t * ui_FaucetCon = NULL;
lv_obj_t * ui_lblFaucet = NULL;
lv_obj_t * ui_swfaucet = NULL;
lv_obj_t * ui_FaucetStat = NULL;
lv_obj_t * ui_BlowerCon = NULL;
lv_obj_t * ui_lblBlower = NULL;
lv_obj_t * ui_swBlower = NULL;
lv_obj_t * ui_BlowerStat = NULL;
lv_obj_t * ui_SoapCon = NULL;
lv_obj_t * ui_lblsoap = NULL;
lv_obj_t * ui_swSoap = NULL;
lv_obj_t * ui_SoapStat = NULL;
lv_obj_t * ui_Container10 = NULL;
lv_obj_t * ui_cpanelwaterquallbl = NULL;
lv_obj_t * ui_cpanelwaterqualstat = NULL;
lv_obj_t * ui_cpanelwifilbl = NULL;
lv_obj_t * ui_cpanelwifistat = NULL;
lv_obj_t * ui_cpanelcoinacclbl = NULL;
lv_obj_t * ui_cpanelcoinaccstat = NULL;
lv_obj_t * ui_cpanelwqstate = NULL;
lv_obj_t * ui_cpanelwifistate = NULL;
lv_obj_t * ui_cpanelccstate = NULL;
lv_obj_t * ui_backbtn3 = NULL;
lv_obj_t * ui_backlbl3 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_testwater = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_testsoap = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_testblower = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_testfaucet = NULL;
lv_obj_t * ui_Label18 = NULL;
// event funtions
void ui_event_swPressure(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        water_switch_changed(e);
    }
}

void ui_event_swfaucet(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        faucet_switch_changed(e);
    }
}

void ui_event_swBlower(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        blower_switch_changed(e);
    }
}

void ui_event_swSoap(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        soap_switch_changed(e);
    }
}

void ui_event_backbtn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        back_to_home(e);
    }
}

void ui_event_testwater(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        water_test_clicked(e);
    }
}

void ui_event_testsoap(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        soap_test_clicked(e);
    }
}

void ui_event_testblower(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        blower_test_clicked(e);
    }
}

void ui_event_testfaucet(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        faucet_test_clicked(e);
    }
}

// build funtions

void ui_AdminPanel_screen_init(void)
{
    ui_AdminPanel = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_AdminPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AdminPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AdminPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_AdminPanel);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -6);
    lv_obj_set_y(ui_Label8, -215);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "ADMIN CONTROL PANEL");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_Label8, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_AdminPanel);
    lv_obj_set_width(ui_Panel2, 767);
    lv_obj_set_height(ui_Panel2, 260);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, -46);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x4C4C4C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WaterCon = lv_obj_create(ui_Panel2);
    lv_obj_remove_style_all(ui_WaterCon);
    lv_obj_set_width(ui_WaterCon, 746);
    lv_obj_set_height(ui_WaterCon, 46);
    lv_obj_set_x(ui_WaterCon, -6);
    lv_obj_set_y(ui_WaterCon, -74);
    lv_obj_set_align(ui_WaterCon, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WaterCon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblPressure = lv_label_create(ui_WaterCon);
    lv_obj_set_width(ui_lblPressure, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPressure, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblPressure, -303);
    lv_obj_set_y(ui_lblPressure, 0);
    lv_obj_set_align(ui_lblPressure, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblPressure, "Water Pressure");
    lv_obj_set_style_text_color(ui_lblPressure, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblPressure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swPressure = lv_switch_create(ui_WaterCon);
    lv_obj_set_width(ui_swPressure, 50);
    lv_obj_set_height(ui_swPressure, 25);
    lv_obj_set_x(ui_swPressure, -72);
    lv_obj_set_y(ui_swPressure, 1);
    lv_obj_set_align(ui_swPressure, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_swPressure, lv_color_hex(0x8D8D8D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swPressure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PressureStat = lv_label_create(ui_WaterCon);
    lv_obj_set_width(ui_PressureStat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PressureStat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PressureStat, -184);
    lv_obj_set_y(ui_PressureStat, -1);
    lv_obj_set_align(ui_PressureStat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PressureStat, "OFF");
    lv_obj_set_style_text_color(ui_PressureStat, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PressureStat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FaucetCon = lv_obj_create(ui_AdminPanel);
    lv_obj_remove_style_all(ui_FaucetCon);
    lv_obj_set_width(ui_FaucetCon, 745);
    lv_obj_set_height(ui_FaucetCon, 32);
    lv_obj_set_x(ui_FaucetCon, -8);
    lv_obj_set_y(ui_FaucetCon, 8);
    lv_obj_set_align(ui_FaucetCon, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_FaucetCon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblFaucet = lv_label_create(ui_FaucetCon);
    lv_obj_set_width(ui_lblFaucet, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblFaucet, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblFaucet, -330);
    lv_obj_set_y(ui_lblFaucet, 0);
    lv_obj_set_align(ui_lblFaucet, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblFaucet, "Faucet");
    lv_obj_set_style_text_color(ui_lblFaucet, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblFaucet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swfaucet = lv_switch_create(ui_FaucetCon);
    lv_obj_set_width(ui_swfaucet, 50);
    lv_obj_set_height(ui_swfaucet, 25);
    lv_obj_set_x(ui_swfaucet, -70);
    lv_obj_set_y(ui_swfaucet, -2);
    lv_obj_set_align(ui_swfaucet, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_swfaucet, lv_color_hex(0x8D8D8D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swfaucet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FaucetStat = lv_label_create(ui_FaucetCon);
    lv_obj_set_width(ui_FaucetStat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FaucetStat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FaucetStat, -181);
    lv_obj_set_y(ui_FaucetStat, -3);
    lv_obj_set_align(ui_FaucetStat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FaucetStat, "OFF");
    lv_obj_set_style_text_color(ui_FaucetStat, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FaucetStat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BlowerCon = lv_obj_create(ui_AdminPanel);
    lv_obj_remove_style_all(ui_BlowerCon);
    lv_obj_set_width(ui_BlowerCon, 745);
    lv_obj_set_height(ui_BlowerCon, 32);
    lv_obj_set_x(ui_BlowerCon, -6);
    lv_obj_set_y(ui_BlowerCon, -33);
    lv_obj_set_align(ui_BlowerCon, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BlowerCon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblBlower = lv_label_create(ui_BlowerCon);
    lv_obj_set_width(ui_lblBlower, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBlower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBlower, -331);
    lv_obj_set_y(ui_lblBlower, 1);
    lv_obj_set_align(ui_lblBlower, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBlower, "Blower");
    lv_obj_set_style_text_color(ui_lblBlower, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBlower, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swBlower = lv_switch_create(ui_BlowerCon);
    lv_obj_set_width(ui_swBlower, 50);
    lv_obj_set_height(ui_swBlower, 25);
    lv_obj_set_x(ui_swBlower, -72);
    lv_obj_set_y(ui_swBlower, -1);
    lv_obj_set_align(ui_swBlower, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_swBlower, lv_color_hex(0x8D8D8D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swBlower, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BlowerStat = lv_label_create(ui_BlowerCon);
    lv_obj_set_width(ui_BlowerStat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BlowerStat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BlowerStat, -183);
    lv_obj_set_y(ui_BlowerStat, 1);
    lv_obj_set_align(ui_BlowerStat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BlowerStat, "OFF");
    lv_obj_set_style_text_color(ui_BlowerStat, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BlowerStat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SoapCon = lv_obj_create(ui_AdminPanel);
    lv_obj_remove_style_all(ui_SoapCon);
    lv_obj_set_width(ui_SoapCon, 756);
    lv_obj_set_height(ui_SoapCon, 32);
    lv_obj_set_x(ui_SoapCon, -1);
    lv_obj_set_y(ui_SoapCon, -80);
    lv_obj_set_align(ui_SoapCon, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SoapCon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblsoap = lv_label_create(ui_SoapCon);
    lv_obj_set_width(ui_lblsoap, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblsoap, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblsoap, -343);
    lv_obj_set_y(ui_lblsoap, 3);
    lv_obj_set_align(ui_lblsoap, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblsoap, "Soap");
    lv_obj_set_style_text_color(ui_lblsoap, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblsoap, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swSoap = lv_switch_create(ui_SoapCon);
    lv_obj_set_width(ui_swSoap, 50);
    lv_obj_set_height(ui_swSoap, 25);
    lv_obj_set_x(ui_swSoap, -76);
    lv_obj_set_y(ui_swSoap, 0);
    lv_obj_set_align(ui_swSoap, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_swSoap, lv_color_hex(0x8D8D8D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swSoap, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SoapStat = lv_label_create(ui_SoapCon);
    lv_obj_set_width(ui_SoapStat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SoapStat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SoapStat, -188);
    lv_obj_set_y(ui_SoapStat, 5);
    lv_obj_set_align(ui_SoapStat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SoapStat, "OFF");
    lv_obj_set_style_text_color(ui_SoapStat, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SoapStat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container10 = lv_obj_create(ui_AdminPanel);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, 214);
    lv_obj_set_height(ui_Container10, 242);
    lv_obj_set_x(ui_Container10, 258);
    lv_obj_set_y(ui_Container10, -47);
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cpanelwaterquallbl = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_cpanelwaterquallbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cpanelwaterquallbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cpanelwaterquallbl, -51);
    lv_obj_set_y(ui_cpanelwaterquallbl, -103);
    lv_obj_set_align(ui_cpanelwaterquallbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cpanelwaterquallbl, "Water Quality");
    lv_obj_set_style_text_color(ui_cpanelwaterquallbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cpanelwaterquallbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cpanelwaterqualstat = lv_obj_create(ui_Container10);
    lv_obj_set_width(ui_cpanelwaterqualstat, 19);
    lv_obj_set_height(ui_cpanelwaterqualstat, 14);
    lv_obj_set_x(ui_cpanelwaterqualstat, 10);
    lv_obj_set_y(ui_cpanelwaterqualstat, -103);
    lv_obj_set_align(ui_cpanelwaterqualstat, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_cpanelwaterqualstat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_cpanelwaterqualstat, lv_color_hex(0x0DFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpanelwaterqualstat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cpanelwifilbl = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_cpanelwifilbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cpanelwifilbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cpanelwifilbl, -85);
    lv_obj_set_y(ui_cpanelwifilbl, -65);
    lv_obj_set_align(ui_cpanelwifilbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cpanelwifilbl, "Wifi");
    lv_obj_set_style_text_color(ui_cpanelwifilbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cpanelwifilbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cpanelwifistat = lv_obj_create(ui_Container10);
    lv_obj_set_width(ui_cpanelwifistat, 19);
    lv_obj_set_height(ui_cpanelwifistat, 14);
    lv_obj_set_x(ui_cpanelwifistat, -55);
    lv_obj_set_y(ui_cpanelwifistat, -65);
    lv_obj_set_align(ui_cpanelwifistat, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_cpanelwifistat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_cpanelwifistat, lv_color_hex(0x0DFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpanelwifistat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cpanelcoinacclbl = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_cpanelcoinacclbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cpanelcoinacclbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cpanelcoinacclbl, -85);
    lv_obj_set_y(ui_cpanelcoinacclbl, -26);
    lv_obj_set_align(ui_cpanelcoinacclbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cpanelcoinacclbl, "ESP32");
    lv_obj_set_style_text_color(ui_cpanelcoinacclbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cpanelcoinacclbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cpanelcoinaccstat = lv_obj_create(ui_Container10);
    lv_obj_set_width(ui_cpanelcoinaccstat, 19);
    lv_obj_set_height(ui_cpanelcoinaccstat, 14);
    lv_obj_set_x(ui_cpanelcoinaccstat, -50);
    lv_obj_set_y(ui_cpanelcoinaccstat, -26);
    lv_obj_set_align(ui_cpanelcoinaccstat, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_cpanelcoinaccstat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(
    ui_cpanelcoinaccstat,
    lv_color_hex(0xFF0000),
    LV_PART_MAIN | LV_STATE_DEFAULT
);
    lv_obj_set_style_bg_opa(ui_cpanelcoinaccstat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cpanelwqstate = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_cpanelwqstate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cpanelwqstate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cpanelwqstate, 64);
    lv_obj_set_y(ui_cpanelwqstate, -104);
    lv_obj_set_align(ui_cpanelwqstate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cpanelwqstate, "EXCELLENT");
    lv_obj_set_style_text_color(ui_cpanelwqstate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cpanelwqstate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cpanelwifistate = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_cpanelwifistate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cpanelwifistate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cpanelwifistate, -14);
    lv_obj_set_y(ui_cpanelwifistate, -64);
    lv_obj_set_align(ui_cpanelwifistate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cpanelwifistate, "ONLINE");
    lv_obj_set_style_text_color(ui_cpanelwifistate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cpanelwifistate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cpanelccstate = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_cpanelccstate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cpanelccstate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cpanelccstate, -9);
    lv_obj_set_y(ui_cpanelccstate, -26);
    lv_obj_set_align(ui_cpanelccstate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cpanelccstate, "OFFLINE");
    lv_obj_set_style_text_color(ui_cpanelccstate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cpanelccstate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backbtn3 = lv_btn_create(ui_AdminPanel);
    lv_obj_set_width(ui_backbtn3, 82);
    lv_obj_set_height(ui_backbtn3, 38);
    lv_obj_set_x(ui_backbtn3, -348);
    lv_obj_set_y(ui_backbtn3, -209);
    lv_obj_set_align(ui_backbtn3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backbtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backbtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backbtn3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backbtn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backlbl3 = lv_label_create(ui_backbtn3);
    lv_obj_set_width(ui_backlbl3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backlbl3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_backlbl3, -2);
    lv_obj_set_y(ui_backlbl3, 0);
    lv_obj_set_align(ui_backlbl3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_backlbl3, "Back");
    lv_obj_set_style_text_color(ui_backlbl3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_backlbl3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_AdminPanel);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -81);
    lv_obj_set_y(ui_Label10, -148);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "ON/OFF");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_AdminPanel);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -189);
    lv_obj_set_y(ui_Label11, -147);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Enable");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_AdminPanel);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 32);
    lv_obj_set_y(ui_Label12, -148);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Test");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Label12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_testwater = lv_btn_create(ui_AdminPanel);
    lv_obj_set_width(ui_testwater, 66);
    lv_obj_set_height(ui_testwater, 32);
    lv_obj_set_x(ui_testwater, 35);
    lv_obj_set_y(ui_testwater, -120);
    lv_obj_set_align(ui_testwater, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_testwater, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_testwater, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_testwater);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -1);
    lv_obj_set_y(ui_Label14, -1);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Test");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Label14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_testsoap = lv_btn_create(ui_AdminPanel);
    lv_obj_set_width(ui_testsoap, 66);
    lv_obj_set_height(ui_testsoap, 32);
    lv_obj_set_x(ui_testsoap, 35);
    lv_obj_set_y(ui_testsoap, -80);
    lv_obj_set_align(ui_testsoap, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_testsoap, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_testsoap, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label16 = lv_label_create(ui_testsoap);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -1);
    lv_obj_set_y(ui_Label16, -1);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Test");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Label16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_testblower = lv_btn_create(ui_AdminPanel);
    lv_obj_set_width(ui_testblower, 66);
    lv_obj_set_height(ui_testblower, 32);
    lv_obj_set_x(ui_testblower, 36);
    lv_obj_set_y(ui_testblower, -39);
    lv_obj_set_align(ui_testblower, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_testblower, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_testblower, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_testblower);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -1);
    lv_obj_set_y(ui_Label17, -1);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Test");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Label17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_testfaucet = lv_btn_create(ui_AdminPanel);
    lv_obj_set_width(ui_testfaucet, 66);
    lv_obj_set_height(ui_testfaucet, 32);
    lv_obj_set_x(ui_testfaucet, 35);
    lv_obj_set_y(ui_testfaucet, 4);
    lv_obj_set_align(ui_testfaucet, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_testfaucet, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_testfaucet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_testfaucet);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -1);
    lv_obj_set_y(ui_Label18, -1);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Test");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Label18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_swPressure, ui_event_swPressure, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_swfaucet, ui_event_swfaucet, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_swBlower, ui_event_swBlower, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_swSoap, ui_event_swSoap, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backbtn3, ui_event_backbtn3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_testwater, ui_event_testwater, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_testsoap, ui_event_testsoap, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_testblower, ui_event_testblower, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_testfaucet, ui_event_testfaucet, LV_EVENT_ALL, NULL);

}

void ui_AdminPanel_screen_destroy(void)
{
    if(ui_AdminPanel) lv_obj_del(ui_AdminPanel);

    // NULL screen variables
    ui_AdminPanel = NULL;
    ui_Label8 = NULL;
    ui_Panel2 = NULL;
    ui_WaterCon = NULL;
    ui_lblPressure = NULL;
    ui_swPressure = NULL;
    ui_PressureStat = NULL;
    ui_FaucetCon = NULL;
    ui_lblFaucet = NULL;
    ui_swfaucet = NULL;
    ui_FaucetStat = NULL;
    ui_BlowerCon = NULL;
    ui_lblBlower = NULL;
    ui_swBlower = NULL;
    ui_BlowerStat = NULL;
    ui_SoapCon = NULL;
    ui_lblsoap = NULL;
    ui_swSoap = NULL;
    ui_SoapStat = NULL;
    ui_Container10 = NULL;
    ui_cpanelwaterquallbl = NULL;
    ui_cpanelwaterqualstat = NULL;
    ui_cpanelwifilbl = NULL;
    ui_cpanelwifistat = NULL;
    ui_cpanelcoinacclbl = NULL;
    ui_cpanelcoinaccstat = NULL;
    ui_cpanelwqstate = NULL;
    ui_cpanelwifistate = NULL;
    ui_cpanelccstate = NULL;
    ui_backbtn3 = NULL;
    ui_backlbl3 = NULL;
    ui_Label10 = NULL;
    ui_Label11 = NULL;
    ui_Label12 = NULL;
    ui_testwater = NULL;
    ui_Label14 = NULL;
    ui_testsoap = NULL;
    ui_Label16 = NULL;
    ui_testblower = NULL;
    ui_Label17 = NULL;
    ui_testfaucet = NULL;
    ui_Label18 = NULL;

}
