// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Carwash_UI_LCD

#ifndef UI_COINPAYMENTPAGE_H
#define UI_COINPAYMENTPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_CoinPaymentpage
extern void ui_CoinPaymentpage_screen_init(void);
extern void ui_CoinPaymentpage_screen_destroy(void);
extern lv_obj_t * ui_CoinPaymentpage;
extern lv_obj_t * ui_PaymentMethodlbl2;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Coininsertlbl;
extern lv_obj_t * ui_InsertedCoinlbl;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_AClbl;
extern lv_obj_t * ui_AC5lbl;
extern void ui_event_backbtn(lv_event_t * e);
extern lv_obj_t * ui_backbtn;
extern lv_obj_t * ui_backlbl;
extern void ui_event_Donebtn(lv_event_t * e);
extern lv_obj_t * ui_Donebtn;
extern lv_obj_t * ui_Donelbl;
extern lv_obj_t * ui_timerlbl;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

