// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Carwash_UI_LCD

#include "ui.h"

lv_obj_t * ui_CoinPaymentpage = NULL;
lv_obj_t * ui_PaymentMethodlbl2 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_Coininsertlbl = NULL;
lv_obj_t * ui_InsertedCoinlbl = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_AClbl = NULL;
lv_obj_t * ui_AC5lbl = NULL;
lv_obj_t * ui_backbtn = NULL;
lv_obj_t * ui_backlbl = NULL;
lv_obj_t * ui_Donebtn = NULL;
lv_obj_t * ui_Donelbl = NULL;
lv_obj_t * ui_timerlbl = NULL;
// event funtions
void ui_event_backbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        coin_back_clicked(e);
    }
}

void ui_event_Donebtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        coin_clicked_done(e);
    }
}

// build funtions

void ui_CoinPaymentpage_screen_init(void)
{
    ui_CoinPaymentpage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CoinPaymentpage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CoinPaymentpage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CoinPaymentpage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_CoinPaymentpage, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CoinPaymentpage, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_PaymentMethodlbl2 = lv_label_create(ui_CoinPaymentpage);
    lv_obj_set_width(ui_PaymentMethodlbl2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PaymentMethodlbl2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PaymentMethodlbl2, 3);
    lv_obj_set_y(ui_PaymentMethodlbl2, -220);
    lv_obj_set_align(ui_PaymentMethodlbl2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PaymentMethodlbl2, "Insert Coin ");
    lv_obj_set_style_text_color(ui_PaymentMethodlbl2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PaymentMethodlbl2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PaymentMethodlbl2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_PaymentMethodlbl2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_CoinPaymentpage);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 260);
    lv_obj_set_height(ui_Container2, 185);
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, -40);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Coininsertlbl = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Coininsertlbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Coininsertlbl, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_x(ui_Coininsertlbl, 3);
    lv_obj_set_y(ui_Coininsertlbl, -68);
    lv_obj_set_align(ui_Coininsertlbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Coininsertlbl, "Coin Inserted:");
    lv_obj_set_style_text_color(ui_Coininsertlbl, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Coininsertlbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Coininsertlbl, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_Coininsertlbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InsertedCoinlbl = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_InsertedCoinlbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InsertedCoinlbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_InsertedCoinlbl, 1);
    lv_obj_set_y(ui_InsertedCoinlbl, -25);
    lv_obj_set_align(ui_InsertedCoinlbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_InsertedCoinlbl, "P0.00");
    lv_obj_set_style_text_color(ui_InsertedCoinlbl, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_InsertedCoinlbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_InsertedCoinlbl, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_InsertedCoinlbl, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_InsertedCoinlbl, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_InsertedCoinlbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_CoinPaymentpage);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 135);
    lv_obj_set_height(ui_Container5, 160);
    lv_obj_set_x(ui_Container5, 322);
    lv_obj_set_y(ui_Container5, -149);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container5, lv_color_hex(0x6E6C6C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AClbl = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_AClbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AClbl, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_x(ui_AClbl, -6);
    lv_obj_set_y(ui_AClbl, -65);
    lv_obj_set_align(ui_AClbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AClbl, "Accepted Coin");
    lv_obj_set_style_text_color(ui_AClbl, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AClbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AClbl, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AC5lbl = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_AC5lbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AC5lbl, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_x(ui_AC5lbl, -44);
    lv_obj_set_y(ui_AC5lbl, 1);
    lv_obj_set_align(ui_AC5lbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AC5lbl, "P 5\n\nP 10\n\nP20");
    lv_obj_set_style_text_color(ui_AC5lbl, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AC5lbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AC5lbl, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backbtn = lv_btn_create(ui_CoinPaymentpage);
    lv_obj_set_width(ui_backbtn, 82);
    lv_obj_set_height(ui_backbtn, 38);
    lv_obj_set_x(ui_backbtn, -341);
    lv_obj_set_y(ui_backbtn, -205);
    lv_obj_set_align(ui_backbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backbtn, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backlbl = lv_label_create(ui_backbtn);
    lv_obj_set_width(ui_backlbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backlbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_backlbl, -2);
    lv_obj_set_y(ui_backlbl, 0);
    lv_obj_set_align(ui_backlbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_backlbl, "Back");
    lv_obj_set_style_text_color(ui_backlbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_backlbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Donebtn = lv_btn_create(ui_CoinPaymentpage);
    lv_obj_set_width(ui_Donebtn, 153);
    lv_obj_set_height(ui_Donebtn, 82);
    lv_obj_set_x(ui_Donebtn, 303);
    lv_obj_set_y(ui_Donebtn, 147);
    lv_obj_set_align(ui_Donebtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Donebtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Donebtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Donebtn, lv_color_hex(0x670173), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Donebtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Donelbl = lv_label_create(ui_Donebtn);
    lv_obj_set_width(ui_Donelbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Donelbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Donelbl, 0);
    lv_obj_set_y(ui_Donelbl, 3);
    lv_obj_set_align(ui_Donelbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Donelbl, "Done");
    lv_obj_set_style_text_color(ui_Donelbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Donelbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Donelbl, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_Donelbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timerlbl = lv_label_create(ui_CoinPaymentpage);
    lv_obj_set_width(ui_timerlbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timerlbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timerlbl, 4);
    lv_obj_set_y(ui_timerlbl, -14);
    lv_obj_set_align(ui_timerlbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timerlbl, "30s");
    lv_obj_set_style_text_color(ui_timerlbl, lv_color_hex(0x00FF0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timerlbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timerlbl, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_timerlbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_backbtn, ui_event_backbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Donebtn, ui_event_Donebtn, LV_EVENT_ALL, NULL);

}

void ui_CoinPaymentpage_screen_destroy(void)
{
    if(ui_CoinPaymentpage) lv_obj_del(ui_CoinPaymentpage);

    // NULL screen variables
    ui_CoinPaymentpage = NULL;
    ui_PaymentMethodlbl2 = NULL;
    ui_Container2 = NULL;
    ui_Coininsertlbl = NULL;
    ui_InsertedCoinlbl = NULL;
    ui_Container5 = NULL;
    ui_AClbl = NULL;
    ui_AC5lbl = NULL;
    ui_backbtn = NULL;
    ui_backlbl = NULL;
    ui_Donebtn = NULL;
    ui_Donelbl = NULL;
    ui_timerlbl = NULL;

}
