// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Carwash_UI_LCD

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void start_clicked(lv_event_t * e);
void admin_logo_clicked(lv_event_t * e);
void water_switch_changed(lv_event_t * e);
void faucet_switch_changed(lv_event_t * e);
void blower_switch_changed(lv_event_t * e);
void soap_switch_changed(lv_event_t * e);
void back_to_home(lv_event_t * e);
void water_test_clicked(lv_event_t * e);
void soap_test_clicked(lv_event_t * e);
void blower_test_clicked(lv_event_t * e);
void faucet_test_clicked(lv_event_t * e);
void gcash_clicked(lv_event_t * e);
void coin_clicked(lv_event_t * e);
void coin_back_clicked(lv_event_t * e);
void coin_clicked_done(lv_event_t * e);
void qr_back_clicked(lv_event_t * e);
void addcoin_clicked(lv_event_t * e);
void addgcash_clicked(lv_event_t * e);
void water_clicked(lv_event_t * e);
void soap_clicked(lv_event_t * e);
void blower_clicked(lv_event_t * e);
void faucet_clicked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
