
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Carwash_UI_LCD

#include "carwash_logic.h"
#include <Arduino.h>
#include "ui.h"
#include "uart_comm.h"
#include "commands.h"       


// ======================================================
// ADMIN LOGO 5-TAP
// ======================================================

static uint8_t adminTapCount = 0;
static uint32_t lastTapTime = 0;


// ======================================================
// CUSTOMER FUNCTION SELECTION
//
// true  = customer selected this function
// false = not selected
//
// The LCD only selects the function.
// The PHYSICAL BUTTON starts the timer.
// ======================================================

bool waterSelected  = false;
bool soapSelected   = false;
bool blowerSelected = false;
bool faucetSelected = false;

// ======================================================
// GREEN SELECTION STYLE
//
// These functions add/remove a GREEN outline around
// the selected customer function button.
// ======================================================

static void selectButton(
    lv_obj_t * button
)
{
    if(button == NULL)
        return;

    lv_obj_set_style_border_width(
        button,
        4,
        LV_PART_MAIN
    );

    lv_obj_set_style_border_color(
        button,
        lv_palette_main(LV_PALETTE_GREEN),
        LV_PART_MAIN
    );

    lv_obj_set_style_border_opa(
        button,
        LV_OPA_COVER,
        LV_PART_MAIN
    );
}


static void deselectButton(
    lv_obj_t * button
)
{
    if(button == NULL)
        return;

    lv_obj_set_style_border_width(
        button,
        0,
        LV_PART_MAIN
    );

    lv_obj_set_style_border_opa(
        button,
        LV_OPA_TRANSP,
        LV_PART_MAIN
    );
}


// ======================================================
// CLEAR ALL CUSTOMER SELECTIONS
// ======================================================

static void clearCustomerSelections()
{
    waterSelected  = false;
    soapSelected   = false;
    blowerSelected = false;
    faucetSelected = false;

    deselectButton(ui_waterbtn);
    deselectButton(ui_soapbtn);
    deselectButton(ui_blowerbtn);
    deselectButton(ui_faucetbtn);
}


// ======================================================
// SELECT WATER
// ======================================================

static void selectWater()
{
    clearCustomerSelections();

    waterSelected = true;

    selectButton(ui_waterbtn);

    Serial.println(
        "CUSTOMER SELECTED: WATER"
    );
}

// ======================================================
// SELECT SOAP
// ======================================================

static void selectSoap()
{
    clearCustomerSelections();

    soapSelected = true;

    selectButton(ui_soapbtn);

    Serial.println(
        "CUSTOMER SELECTED: SOAP"
    );
}

// ======================================================
// SELECT BLOWER
// ======================================================

static void selectBlower()
{
    clearCustomerSelections();

    blowerSelected = true;

    selectButton(ui_blowerbtn);

    Serial.println(
        "CUSTOMER SELECTED: BLOWER"
    );
}


// ======================================================
// SELECT FAUCET
// ======================================================

static void selectFaucet()
{
    clearCustomerSelections();

    faucetSelected = true;

    selectButton(ui_faucetbtn);

    Serial.println(
        "CUSTOMER SELECTED: FAUCET"
    );
}

// ======================================================
// START SCREEN
// ======================================================

void start_clicked(lv_event_t * e)
{
    _ui_screen_change(
        &ui_SelectPaymentpage,
        LV_SCR_LOAD_ANIM_NONE,
        0,
        0,
        &ui_SelectPaymentpage_screen_init
    );
}


// ======================================================
// ADMIN LOGO
// 5 TAPS WITHIN 3 SECONDS
// ======================================================

void admin_logo_clicked(lv_event_t * e)
{
    uint32_t now = millis();

    if(now - lastTapTime > 3000)
    {
        adminTapCount = 0;
    }

    lastTapTime = now;
    adminTapCount++;

    if(adminTapCount >= 5)
    {
        adminTapCount = 0;

        _ui_screen_change(
            &ui_AdminPanel,
            LV_SCR_LOAD_ANIM_NONE,
            0,
            0,
            &ui_AdminPanel_screen_init
        );
    }
}


// ======================================================
// GCASH
// ======================================================

void gcash_clicked(lv_event_t * e)
{
    _ui_screen_change(
        &ui_GcashPaymentScreen,
        LV_SCR_LOAD_ANIM_NONE,
        0,
        0,
        &ui_GcashPaymentScreen_screen_init
    );
}


// ======================================================
// COIN
// ======================================================

void coin_clicked(lv_event_t * e)
{
    _ui_screen_change(
        &ui_CoinPaymentpage,
        LV_SCR_LOAD_ANIM_NONE,
        0,
        0,
        &ui_CoinPaymentpage_screen_init
    );
}


// ======================================================
// BACK TO HOME
// ======================================================

void back_to_home(lv_event_t * e)
{
    clearCustomerSelections();

    _ui_screen_change(
        &ui_welcomepage,
        LV_SCR_LOAD_ANIM_NONE,
        0,
        0,
        &ui_welcomepage_screen_init
    );
}


// ======================================================
// COIN BACK
// ======================================================

void coin_back_clicked(lv_event_t * e)
{
    _ui_screen_change(
        &ui_SelectPaymentpage,
        LV_SCR_LOAD_ANIM_NONE,
        0,
        0,
        &ui_SelectPaymentpage_screen_init
    );
}


// ======================================================
// COIN PAYMENT DONE
// ======================================================

void coin_clicked_done(lv_event_t * e)
{
    clearCustomerSelections();

    _ui_screen_change(
        &ui_MainScreen,
        LV_SCR_LOAD_ANIM_NONE,
        0,
        0,
        &ui_MainScreen_screen_init
    );
}


// ======================================================
// QR BACK
// ======================================================

void qr_back_clicked(lv_event_t * e)
{
    _ui_screen_change(
        &ui_GcashPaymentScreen,
        LV_SCR_LOAD_ANIM_NONE,
        0,
        0,
        &ui_GcashPaymentScreen_screen_init
    );
}


// ======================================================
// CUSTOMER WATER
//
// LCD TAP = SELECT WATER
// PHYSICAL BUTTON = START WATER
// ======================================================

void water_clicked(lv_event_t * e)
{
    selectWater();
}


// ======================================================
// CUSTOMER SOAP
//
// LCD TAP = SELECT SOAP
// PHYSICAL BUTTON = START SOAP
// ======================================================

void soap_clicked(lv_event_t * e)
{
    selectSoap();
}


// ======================================================
// CUSTOMER BLOWER
//
// LCD TAP = SELECT BLOWER
// PHYSICAL BUTTON = START BLOWER
// ======================================================

void blower_clicked(lv_event_t * e)
{
    selectBlower();
}


// ======================================================
// CUSTOMER FAUCET
//
// LCD TAP = SELECT FAUCET
// PHYSICAL BUTTON = START FAUCET
// ======================================================

void faucet_clicked(lv_event_t * e)
{
    selectFaucet();
}


// ======================================================
// ADD COIN
// ======================================================

void addcoin_clicked(lv_event_t * e)
{
    // Reserved for future credit system
}


// ======================================================
// ADD GCASH
// ======================================================

void addgcash_clicked(lv_event_t * e)
{
    // Reserved for future credit system
}


// ======================================================
// ADMIN WATER SWITCH
// ======================================================

void water_switch_changed(lv_event_t * e)
{
    lv_obj_t * sw = lv_event_get_target(e);

    if(lv_obj_has_state(sw, LV_STATE_CHECKED))
    {
        setWaterEnabled(true);

        lv_label_set_text(
            ui_PressureStat,
            "ON"
        );

        lv_obj_set_style_text_color(
            ui_PressureStat,
            lv_palette_main(LV_PALETTE_GREEN),
            LV_PART_MAIN
        );
    }
    else
    {
        setWaterEnabled(false);

        // Remove customer selection if disabled
        if(waterSelected)
        {
            waterSelected = false;
            deselectButton(ui_waterbtn);

            lv_label_set_text(
                ui_waterstatus,
                "AVAILABLE"
            );
        }

        lv_label_set_text(
            ui_PressureStat,
            "OFF"
        );

        lv_obj_set_style_text_color(
            ui_PressureStat,
            lv_palette_main(LV_PALETTE_RED),
            LV_PART_MAIN
        );
    }
}


// ======================================================
// ADMIN FAUCET SWITCH
// ======================================================

void faucet_switch_changed(lv_event_t * e)
{
    lv_obj_t * sw = lv_event_get_target(e);

    if(lv_obj_has_state(sw, LV_STATE_CHECKED))
    {
        setFaucetEnabled(true);

        lv_label_set_text(
            ui_FaucetStat,
            "ON"
        );

        lv_obj_set_style_text_color(
            ui_FaucetStat,
            lv_palette_main(LV_PALETTE_GREEN),
            LV_PART_MAIN
        );
    }
    else
    {
        setFaucetEnabled(false);

        if(faucetSelected)
        {
            faucetSelected = false;
            deselectButton(ui_faucetbtn);

            lv_label_set_text(
                ui_faucetstatus,
                "AVAILABLE"
            );
        }

        lv_label_set_text(
            ui_FaucetStat,
            "OFF"
        );

        lv_obj_set_style_text_color(
            ui_FaucetStat,
            lv_palette_main(LV_PALETTE_RED),
            LV_PART_MAIN
        );
    }
}


// ======================================================
// ADMIN BLOWER SWITCH
// ======================================================

void blower_switch_changed(lv_event_t * e)
{
    lv_obj_t * sw = lv_event_get_target(e);

    if(lv_obj_has_state(sw, LV_STATE_CHECKED))
    {
        setBlowerEnabled(true);

        lv_label_set_text(
            ui_BlowerStat,
            "ON"
        );

        lv_obj_set_style_text_color(
            ui_BlowerStat,
            lv_palette_main(LV_PALETTE_GREEN),
            LV_PART_MAIN
        );
    }
    else
    {
        setBlowerEnabled(false);

        if(blowerSelected)
        {
            blowerSelected = false;
            deselectButton(ui_blowerbtn);

            lv_label_set_text(
                ui_blowerstatus,
                "AVAILABLE"
            );
        }

        lv_label_set_text(
            ui_BlowerStat,
            "OFF"
        );

        lv_obj_set_style_text_color(
            ui_BlowerStat,
            lv_palette_main(LV_PALETTE_RED),
            LV_PART_MAIN
        );
    }
}


// ======================================================
// ADMIN SOAP SWITCH
// ======================================================

void soap_switch_changed(lv_event_t * e)
{
    lv_obj_t * sw = lv_event_get_target(e);

    if(lv_obj_has_state(sw, LV_STATE_CHECKED))
    {
        setSoapEnabled(true);

        lv_label_set_text(
            ui_SoapStat,
            "ON"
        );

        lv_obj_set_style_text_color(
            ui_SoapStat,
            lv_palette_main(LV_PALETTE_GREEN),
            LV_PART_MAIN
        );
    }
    else
    {
        setSoapEnabled(false);

        if(soapSelected)
        {
            soapSelected = false;
            deselectButton(ui_soapbtn);

            lv_label_set_text(
                ui_soapstatus,
                "AVAILABLE"
            );
        }

        lv_label_set_text(
            ui_SoapStat,
            "OFF"
        );

        lv_obj_set_style_text_color(
            ui_SoapStat,
            lv_palette_main(LV_PALETTE_RED),
            LV_PART_MAIN
        );
    }
}


// ======================================================
// ADMIN WATER TEST
// ======================================================

void water_test_clicked(lv_event_t * e)
{
    startWaterTest();
}


// ======================================================
// ADMIN SOAP TEST
// ======================================================

void soap_test_clicked(lv_event_t * e)
{
    startSoapTest();
}


// ======================================================
// ADMIN BLOWER TEST
// ======================================================

void blower_test_clicked(lv_event_t * e)
{
    startBlowerTest();
}


// ======================================================
// ADMIN FAUCET TEST
// ======================================================

void faucet_test_clicked(lv_event_t * e)
{
    startFaucetTest();
}
