// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Carwash_UI_LCD

#ifndef UI_GCASHPAYMENTSCREEN_H
#define UI_GCASHPAYMENTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_GcashPaymentScreen
extern void ui_GcashPaymentScreen_screen_init(void);
extern void ui_GcashPaymentScreen_screen_destroy(void);
extern lv_obj_t * ui_GcashPaymentScreen;
extern void ui_event_gcashbackbtn(lv_event_t * e);
extern lv_obj_t * ui_gcashbackbtn;
extern lv_obj_t * ui_gacshbackbtn;
extern lv_obj_t * ui_gcashlbl1;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_AmountoPaylbl;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_amount10cb;
extern lv_obj_t * ui_amount20cb;
extern lv_obj_t * ui_amount30cb;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_GcashCurrentCreditlbl;
extern lv_obj_t * ui_GcashCValCreditlbl;
extern void ui_event_GcashPaybtn(lv_event_t * e);
extern lv_obj_t * ui_GcashPaybtn;
extern lv_obj_t * ui_paylbl;
extern lv_obj_t * ui_Label6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

