// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Carwash_UI_LCD

#ifndef UI_GCASHQRSC_H
#define UI_GCASHQRSC_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_GcashQRsc
extern void ui_GcashQRsc_screen_init(void);
extern void ui_GcashQRsc_screen_destroy(void);
extern lv_obj_t * ui_GcashQRsc;
extern lv_obj_t * ui_cancelpaybtn;
extern lv_obj_t * ui_gcashscanbacklbl;
extern lv_obj_t * ui_scanmelbl;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_lablel111;
extern lv_obj_t * ui_GcashAmountlbl;
extern lv_obj_t * ui_gcashpaymentstat;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_GcashCurrentCreditlbl2;
extern lv_obj_t * ui_GcashCValCreditlbl2;
extern lv_obj_t * ui_qrimagepng;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

