// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Carwash_UI_LCD

#include "ui.h"

lv_obj_t * ui_GcashQRsc = NULL;
lv_obj_t * ui_cancelpaybtn = NULL;
lv_obj_t * ui_gcashscanbacklbl = NULL;
lv_obj_t * ui_scanmelbl = NULL;
lv_obj_t * ui_Container9 = NULL;
lv_obj_t * ui_lablel111 = NULL;
lv_obj_t * ui_GcashAmountlbl = NULL;
lv_obj_t * ui_gcashpaymentstat = NULL;
lv_obj_t * ui_Container12 = NULL;
lv_obj_t * ui_GcashCurrentCreditlbl2 = NULL;
lv_obj_t * ui_GcashCValCreditlbl2 = NULL;
lv_obj_t * ui_qrimagepng = NULL;
// event funtions

// build funtions

void ui_GcashQRsc_screen_init(void)
{
    ui_GcashQRsc = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_GcashQRsc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GcashQRsc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GcashQRsc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cancelpaybtn = lv_btn_create(ui_GcashQRsc);
    lv_obj_set_width(ui_cancelpaybtn, 82);
    lv_obj_set_height(ui_cancelpaybtn, 38);
    lv_obj_set_x(ui_cancelpaybtn, -348);
    lv_obj_set_y(ui_cancelpaybtn, -209);
    lv_obj_set_align(ui_cancelpaybtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cancelpaybtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_cancelpaybtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_cancelpaybtn, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cancelpaybtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gcashscanbacklbl = lv_label_create(ui_cancelpaybtn);
    lv_obj_set_width(ui_gcashscanbacklbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gcashscanbacklbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gcashscanbacklbl, -2);
    lv_obj_set_y(ui_gcashscanbacklbl, 0);
    lv_obj_set_align(ui_gcashscanbacklbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gcashscanbacklbl, "Back");

    ui_scanmelbl = lv_label_create(ui_GcashQRsc);
    lv_obj_set_width(ui_scanmelbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scanmelbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scanmelbl, -49);
    lv_obj_set_y(ui_scanmelbl, -201);
    lv_obj_set_align(ui_scanmelbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scanmelbl, "SCAN ME!");
    lv_obj_set_style_text_color(ui_scanmelbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_scanmelbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_scanmelbl, 600, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container9 = lv_obj_create(ui_GcashQRsc);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 318);
    lv_obj_set_height(ui_Container9, 349);
    lv_obj_set_x(ui_Container9, 0);
    lv_obj_set_y(ui_Container9, 7);
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lablel111 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_lablel111, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lablel111, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lablel111, 6);
    lv_obj_set_y(ui_lablel111, 39);
    lv_obj_set_align(ui_lablel111, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lablel111, "Amount to Pay:");
    lv_obj_set_style_text_color(ui_lablel111, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lablel111, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GcashAmountlbl = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_GcashAmountlbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GcashAmountlbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GcashAmountlbl, -7);
    lv_obj_set_y(ui_GcashAmountlbl, 70);
    lv_obj_set_align(ui_GcashAmountlbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GcashAmountlbl, "0.00");
    lv_obj_set_style_text_color(ui_GcashAmountlbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GcashAmountlbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_GcashAmountlbl, 400, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gcashpaymentstat = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_gcashpaymentstat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gcashpaymentstat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gcashpaymentstat, -6);
    lv_obj_set_y(ui_gcashpaymentstat, 131);
    lv_obj_set_align(ui_gcashpaymentstat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gcashpaymentstat, "Waiting......");
    lv_obj_set_style_text_color(ui_gcashpaymentstat, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gcashpaymentstat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container12 = lv_obj_create(ui_GcashQRsc);
    lv_obj_remove_style_all(ui_Container12);
    lv_obj_set_width(ui_Container12, 129);
    lv_obj_set_height(ui_Container12, 162);
    lv_obj_set_x(ui_Container12, -323);
    lv_obj_set_y(ui_Container12, 243);
    lv_obj_set_align(ui_Container12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_letter_space(ui_Container12, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Container12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GcashCurrentCreditlbl2 = lv_label_create(ui_Container12);
    lv_obj_set_width(ui_GcashCurrentCreditlbl2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GcashCurrentCreditlbl2, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_x(ui_GcashCurrentCreditlbl2, 4);
    lv_obj_set_y(ui_GcashCurrentCreditlbl2, -64);
    lv_obj_set_align(ui_GcashCurrentCreditlbl2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GcashCurrentCreditlbl2, "Current Credit:");
    lv_obj_set_style_text_color(ui_GcashCurrentCreditlbl2, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GcashCurrentCreditlbl2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GcashCValCreditlbl2 = lv_label_create(ui_Container12);
    lv_obj_set_width(ui_GcashCValCreditlbl2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GcashCValCreditlbl2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GcashCValCreditlbl2, -7);
    lv_obj_set_y(ui_GcashCValCreditlbl2, -40);
    lv_obj_set_align(ui_GcashCValCreditlbl2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GcashCValCreditlbl2, "P0.00");
    lv_obj_set_style_text_color(ui_GcashCValCreditlbl2, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GcashCValCreditlbl2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_GcashCValCreditlbl2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_GcashCValCreditlbl2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GcashCValCreditlbl2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_GcashCValCreditlbl2, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_qrimagepng = lv_img_create(ui_GcashQRsc);
    lv_obj_set_width(ui_qrimagepng, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_qrimagepng, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_qrimagepng, -4);
    lv_obj_set_y(ui_qrimagepng, -68);
    lv_obj_set_align(ui_qrimagepng, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_qrimagepng, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_qrimagepng, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_GcashQRsc_screen_destroy(void)
{
    if(ui_GcashQRsc) lv_obj_del(ui_GcashQRsc);

    // NULL screen variables
    ui_GcashQRsc = NULL;
    ui_cancelpaybtn = NULL;
    ui_gcashscanbacklbl = NULL;
    ui_scanmelbl = NULL;
    ui_Container9 = NULL;
    ui_lablel111 = NULL;
    ui_GcashAmountlbl = NULL;
    ui_gcashpaymentstat = NULL;
    ui_Container12 = NULL;
    ui_GcashCurrentCreditlbl2 = NULL;
    ui_GcashCValCreditlbl2 = NULL;
    ui_qrimagepng = NULL;

}
