
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Carwash_UI_LCD

#include "ui.h"
#include <stdio.h>

lv_obj_t * ui_GcashPaymentScreen = NULL;
lv_obj_t * ui_gcashbackbtn = NULL;
lv_obj_t * ui_gacshbackbtn = NULL;
lv_obj_t * ui_gcashlbl1 = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_AmountoPaylbl = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_amount10cb = NULL;
lv_obj_t * ui_amount20cb = NULL;
lv_obj_t * ui_amount30cb = NULL;
lv_obj_t * ui_Container8 = NULL;
lv_obj_t * ui_GcashCurrentCreditlbl = NULL;
lv_obj_t * ui_GcashCValCreditlbl = NULL;
lv_obj_t * ui_GcashPaybtn = NULL;
lv_obj_t * ui_paylbl = NULL;
lv_obj_t * ui_Label6 = NULL;


// ============================================================
// SELECTED GCASH AMOUNT
// ============================================================

volatile uint16_t gcashSelectedAmount = 0;


// ============================================================
// EVENT FUNCTIONS
// ============================================================

// FIX 1:
// gcashbackbtn is the actual Cancel button.
//
// IMPORTANT:
// DO NOT call qr_back_clicked() here.
// qr_back_clicked() reloads ui_GcashPaymentScreen.
//
// coin_back_clicked() takes the user back to
// ui_SelectPaymentpage.

void ui_event_gcashbackbtn(lv_event_t * e)
{
    if(e == NULL)
        return;

    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED)
    {
        gcashSelectedAmount = 0;

        if(ui_amount10cb)
            lv_obj_clear_state(
                ui_amount10cb,
                LV_STATE_CHECKED
            );

        if(ui_amount20cb)
            lv_obj_clear_state(
                ui_amount20cb,
                LV_STATE_CHECKED
            );

        if(ui_amount30cb)
            lv_obj_clear_state(
                ui_amount30cb,
                LV_STATE_CHECKED
            );

        if(ui_AmountoPaylbl)
            lv_label_set_text(
                ui_AmountoPaylbl,
                "PHP 0.00"
            );

        // CORRECT BACK FUNCTION
        coin_back_clicked(e);
    }
}


// ============================================================
// AMOUNT 10
// ============================================================

static void ui_event_amount10cb(lv_event_t * e)
{
    if(e == NULL)
        return;

    if(lv_event_get_code(e) == LV_EVENT_CLICKED)
    {
        gcashSelectedAmount = 10;

        lv_obj_add_state(
            ui_amount10cb,
            LV_STATE_CHECKED
        );

        lv_obj_clear_state(
            ui_amount20cb,
            LV_STATE_CHECKED
        );

        lv_obj_clear_state(
            ui_amount30cb,
            LV_STATE_CHECKED
        );

        lv_label_set_text(
            ui_AmountoPaylbl,
            "PHP 10.00"
        );
    }
}


// ============================================================
// AMOUNT 20
// ============================================================

static void ui_event_amount20cb(lv_event_t * e)
{
    if(e == NULL)
        return;

    if(lv_event_get_code(e) == LV_EVENT_CLICKED)
    {
        gcashSelectedAmount = 20;

        lv_obj_clear_state(
            ui_amount10cb,
            LV_STATE_CHECKED
        );

        lv_obj_add_state(
            ui_amount20cb,
            LV_STATE_CHECKED
        );

        lv_obj_clear_state(
            ui_amount30cb,
            LV_STATE_CHECKED
        );

        lv_label_set_text(
            ui_AmountoPaylbl,
            "PHP 20.00"
        );
    }
}


// ============================================================
// AMOUNT 30
// ============================================================

static void ui_event_amount30cb(lv_event_t * e)
{
    if(e == NULL)
        return;

    if(lv_event_get_code(e) == LV_EVENT_CLICKED)
    {
        gcashSelectedAmount = 30;

        lv_obj_clear_state(
            ui_amount10cb,
            LV_STATE_CHECKED
        );

        lv_obj_clear_state(
            ui_amount20cb,
            LV_STATE_CHECKED
        );

        lv_obj_add_state(
            ui_amount30cb,
            LV_STATE_CHECKED
        );

        lv_label_set_text(
            ui_AmountoPaylbl,
            "PHP 30.00"
        );
    }
}


// ============================================================
// PAY BUTTON
// ============================================================

void ui_event_GcashPaybtn(lv_event_t * e)
{
    if(e == NULL)
        return;

    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED)
    {
        // Pay button -> proceed to the GCash QR screen.
        // Do not call gcash_clicked() here; that function returns
        // to/reloads the amount-selection screen.
        if(gcashSelectedAmount == 0)
        {
            // No amount selected yet. Stay on this screen.
            return;
        }

        // Show the selected amount on the QR screen.
        if(ui_GcashAmountlbl)
        {
            char amountText[16];
            snprintf(amountText, sizeof(amountText), "%u.00", gcashSelectedAmount);
            lv_label_set_text(ui_GcashAmountlbl, amountText);
        }

        _ui_screen_change(
            &ui_GcashQRsc,
            LV_SCR_LOAD_ANIM_NONE,
            0,
            0,
            &ui_GcashQRsc_screen_init
        );
    }
}


// ============================================================
// BUILD FUNCTIONS
// ============================================================

void ui_GcashPaymentScreen_screen_init(void)
{
    ui_GcashPaymentScreen = lv_obj_create(NULL);

    lv_obj_clear_flag(
        ui_GcashPaymentScreen,
        LV_OBJ_FLAG_SCROLLABLE
    );

    lv_obj_set_style_bg_color(
        ui_GcashPaymentScreen,
        lv_color_hex(0x000000),
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_bg_opa(
        ui_GcashPaymentScreen,
        255,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );


    // ========================================================
    // BACK / CANCEL BUTTON
    // ========================================================

    ui_gcashbackbtn =
        lv_btn_create(ui_GcashPaymentScreen);

    lv_obj_set_width(
        ui_gcashbackbtn,
        82
    );

    lv_obj_set_height(
        ui_gcashbackbtn,
        38
    );

    lv_obj_set_x(
        ui_gcashbackbtn,
        -344
    );

    lv_obj_set_y(
        ui_gcashbackbtn,
        -208
    );

    lv_obj_set_align(
        ui_gcashbackbtn,
        LV_ALIGN_CENTER
    );

    lv_obj_add_flag(
        ui_gcashbackbtn,
        LV_OBJ_FLAG_SCROLL_ON_FOCUS
    );

    lv_obj_clear_flag(
        ui_gcashbackbtn,
        LV_OBJ_FLAG_SCROLLABLE
    );

    lv_obj_set_style_bg_color(
        ui_gcashbackbtn,
        lv_color_hex(0xFF0000),
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_bg_opa(
        ui_gcashbackbtn,
        255,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );


    // ========================================================
    // CANCEL LABEL
    // ========================================================

    ui_gacshbackbtn =
        lv_label_create(ui_gcashbackbtn);

    lv_obj_set_width(
        ui_gacshbackbtn,
        LV_SIZE_CONTENT
    );

    lv_obj_set_height(
        ui_gacshbackbtn,
        LV_SIZE_CONTENT
    );

    lv_obj_set_x(
        ui_gacshbackbtn,
        -1
    );

    lv_obj_set_y(
        ui_gacshbackbtn,
        -1
    );

    lv_obj_set_align(
        ui_gacshbackbtn,
        LV_ALIGN_CENTER
    );

    lv_label_set_text(
        ui_gacshbackbtn,
        "Cancel"
    );

    lv_obj_set_style_text_color(
        ui_gacshbackbtn,
        lv_color_hex(0xFBFBFB),
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_opa(
        ui_gacshbackbtn,
        255,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );


    // ========================================================
    // TITLE
    // ========================================================

    ui_gcashlbl1 =
        lv_label_create(ui_GcashPaymentScreen);

    lv_obj_set_width(
        ui_gcashlbl1,
        LV_SIZE_CONTENT
    );

    lv_obj_set_height(
        ui_gcashlbl1,
        LV_SIZE_CONTENT
    );

    lv_obj_set_x(
        ui_gcashlbl1,
        2
    );

    lv_obj_set_y(
        ui_gcashlbl1,
        -185
    );

    lv_obj_set_align(
        ui_gcashlbl1,
        LV_ALIGN_CENTER
    );

    lv_label_set_text(
        ui_gcashlbl1,
        "Select Amount to Pay"
    );

    lv_obj_set_style_text_color(
        ui_gcashlbl1,
        lv_color_hex(0xFFFFFF),
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_opa(
        ui_gcashlbl1,
        255,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_font(
        ui_gcashlbl1,
        &lv_font_montserrat_22,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_transform_zoom(
        ui_gcashlbl1,
        256,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );


    // ========================================================
    // AMOUNT DISPLAY CONTAINER
    // ========================================================

    ui_Container7 =
        lv_obj_create(ui_GcashPaymentScreen);

    lv_obj_remove_style_all(
        ui_Container7
    );

    lv_obj_set_width(
        ui_Container7,
        251
    );

    lv_obj_set_height(
        ui_Container7,
        76
    );

    lv_obj_set_x(
        ui_Container7,
        -21
    );

    lv_obj_set_y(
        ui_Container7,
        -97
    );

    lv_obj_set_align(
        ui_Container7,
        LV_ALIGN_CENTER
    );

    lv_obj_clear_flag(
        ui_Container7,
        LV_OBJ_FLAG_CLICKABLE |
        LV_OBJ_FLAG_SCROLLABLE
    );


    ui_AmountoPaylbl =
        lv_label_create(ui_Container7);

    lv_obj_set_width(
        ui_AmountoPaylbl,
        LV_SIZE_CONTENT
    );

    lv_obj_set_height(
        ui_AmountoPaylbl,
        LV_SIZE_CONTENT
    );

    lv_obj_set_x(
        ui_AmountoPaylbl,
        18
    );

    lv_obj_set_y(
        ui_AmountoPaylbl,
        -22
    );

    lv_obj_set_align(
        ui_AmountoPaylbl,
        LV_ALIGN_CENTER
    );

    // FIX 3:
    // PHP instead of peso symbol to preserve existing font.

    lv_label_set_text(
        ui_AmountoPaylbl,
        "PHP 0.00"
    );

    lv_obj_set_style_text_color(
        ui_AmountoPaylbl,
        lv_color_hex(0xFDFBFB),
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_opa(
        ui_AmountoPaylbl,
        255,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_letter_space(
        ui_AmountoPaylbl,
        1,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_line_space(
        ui_AmountoPaylbl,
        3,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_font(
        ui_AmountoPaylbl,
        &lv_font_montserrat_28,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_transform_zoom(
        ui_AmountoPaylbl,
        256,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );


    // ========================================================
    // AMOUNT CHECKBOX CONTAINER
    // ========================================================

    ui_Container6 =
        lv_obj_create(ui_GcashPaymentScreen);

    lv_obj_remove_style_all(
        ui_Container6
    );

    lv_obj_set_width(
        ui_Container6,
        295
    );

    lv_obj_set_height(
        ui_Container6,
        54
    );

    lv_obj_set_x(
        ui_Container6,
        11
    );

    lv_obj_set_y(
        ui_Container6,
        -25
    );

    lv_obj_set_align(
        ui_Container6,
        LV_ALIGN_CENTER
    );

    lv_obj_clear_flag(
        ui_Container6,
        LV_OBJ_FLAG_CLICKABLE |
        LV_OBJ_FLAG_SCROLLABLE
    );


    // ========================================================
    // 10
    // ========================================================

    ui_amount10cb =
        lv_checkbox_create(ui_Container6);

    lv_checkbox_set_text(
        ui_amount10cb,
        "10"
    );

    lv_obj_set_width(
        ui_amount10cb,
        LV_SIZE_CONTENT
    );

    lv_obj_set_height(
        ui_amount10cb,
        LV_SIZE_CONTENT
    );

    lv_obj_set_x(
        ui_amount10cb,
        -98
    );

    lv_obj_set_y(
        ui_amount10cb,
        6
    );

    lv_obj_set_align(
        ui_amount10cb,
        LV_ALIGN_CENTER
    );

    lv_obj_add_flag(
        ui_amount10cb,
        LV_OBJ_FLAG_SCROLL_ON_FOCUS
    );

    lv_obj_set_style_text_color(
        ui_amount10cb,
        lv_color_hex(0xFFFFFF),
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_opa(
        ui_amount10cb,
        255,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );


    // ========================================================
    // 20
    // ========================================================

    ui_amount20cb =
        lv_checkbox_create(ui_Container6);

    lv_checkbox_set_text(
        ui_amount20cb,
        "20"
    );

    lv_obj_set_width(
        ui_amount20cb,
        LV_SIZE_CONTENT
    );

    lv_obj_set_height(
        ui_amount20cb,
        LV_SIZE_CONTENT
    );

    lv_obj_set_x(
        ui_amount20cb,
        7
    );

    lv_obj_set_y(
        ui_amount20cb,
        7
    );

    lv_obj_set_align(
        ui_amount20cb,
        LV_ALIGN_CENTER
    );

    lv_obj_add_flag(
        ui_amount20cb,
        LV_OBJ_FLAG_SCROLL_ON_FOCUS
    );

    lv_obj_set_style_text_color(
        ui_amount20cb,
        lv_color_hex(0xFFFFFF),
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_opa(
        ui_amount20cb,
        255,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );


    // ========================================================
    // 30
    // ========================================================

    ui_amount30cb =
        lv_checkbox_create(ui_Container6);

    lv_checkbox_set_text(
        ui_amount30cb,
        "30"
    );

    lv_obj_set_width(
        ui_amount30cb,
        LV_SIZE_CONTENT
    );

    lv_obj_set_height(
        ui_amount30cb,
        LV_SIZE_CONTENT
    );

    lv_obj_set_x(
        ui_amount30cb,
        101
    );

    lv_obj_set_y(
        ui_amount30cb,
        7
    );

    lv_obj_set_align(
        ui_amount30cb,
        LV_ALIGN_CENTER
    );

    lv_obj_add_flag(
        ui_amount30cb,
        LV_OBJ_FLAG_SCROLL_ON_FOCUS
    );

    lv_obj_set_style_text_color(
        ui_amount30cb,
        lv_color_hex(0xFFFFFF),
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_opa(
        ui_amount30cb,
        255,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );


    // ========================================================
    // CURRENT CREDIT CONTAINER
    // ========================================================

    ui_Container8 =
        lv_obj_create(ui_GcashPaymentScreen);

    lv_obj_remove_style_all(
        ui_Container8
    );

    lv_obj_set_width(
        ui_Container8,
        129
    );

    lv_obj_set_height(
        ui_Container8,
        162
    );

    lv_obj_set_x(
        ui_Container8,
        -323
    );

    lv_obj_set_y(
        ui_Container8,
        243
    );

    lv_obj_set_align(
        ui_Container8,
        LV_ALIGN_CENTER
    );

    lv_obj_clear_flag(
        ui_Container8,
        LV_OBJ_FLAG_CLICKABLE |
        LV_OBJ_FLAG_SCROLLABLE
    );

    lv_obj_set_style_text_letter_space(
        ui_Container8,
        1,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_line_space(
        ui_Container8,
        0,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );


    // ========================================================
    // CURRENT CREDIT LABEL
    // ========================================================

    ui_GcashCurrentCreditlbl =
        lv_label_create(ui_Container8);

    lv_obj_set_width(
        ui_GcashCurrentCreditlbl,
        LV_SIZE_CONTENT
    );

    lv_obj_set_height(
        ui_GcashCurrentCreditlbl,
        LV_SIZE_CONTENT
    );

    lv_obj_set_x(
        ui_GcashCurrentCreditlbl,
        4
    );

    lv_obj_set_y(
        ui_GcashCurrentCreditlbl,
        -64
    );

    lv_obj_set_align(
        ui_GcashCurrentCreditlbl,
        LV_ALIGN_CENTER
    );

    lv_label_set_text(
        ui_GcashCurrentCreditlbl,
        "Current Credit:"
    );

    lv_obj_set_style_text_color(
        ui_GcashCurrentCreditlbl,
        lv_color_hex(0xFDFBFB),
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_opa(
        ui_GcashCurrentCreditlbl,
        255,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );


    // ========================================================
    // CURRENT CREDIT VALUE
    // ========================================================

    ui_GcashCValCreditlbl =
        lv_label_create(ui_Container8);

    lv_obj_set_width(
        ui_GcashCValCreditlbl,
        LV_SIZE_CONTENT
    );

    lv_obj_set_height(
        ui_GcashCValCreditlbl,
        LV_SIZE_CONTENT
    );

    lv_obj_set_x(
        ui_GcashCValCreditlbl,
        -7
    );

    lv_obj_set_y(
        ui_GcashCValCreditlbl,
        -40
    );

    lv_obj_set_align(
        ui_GcashCValCreditlbl,
        LV_ALIGN_CENTER
    );

    lv_label_set_text(
        ui_GcashCValCreditlbl,
        "P0.00"
    );

    lv_obj_set_style_text_color(
        ui_GcashCValCreditlbl,
        lv_color_hex(0xFDFBFB),
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_opa(
        ui_GcashCValCreditlbl,
        255,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_letter_space(
        ui_GcashCValCreditlbl,
        1,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_line_space(
        ui_GcashCValCreditlbl,
        3,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_font(
        ui_GcashCValCreditlbl,
        &lv_font_montserrat_20,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_transform_zoom(
        ui_GcashCValCreditlbl,
        256,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );


    // ========================================================
    // PAY BUTTON
    // ========================================================

    ui_GcashPaybtn =
        lv_btn_create(ui_GcashPaymentScreen);

    lv_obj_set_width(
        ui_GcashPaybtn,
        183
    );

    lv_obj_set_height(
        ui_GcashPaybtn,
        74
    );

    lv_obj_set_x(
        ui_GcashPaybtn,
        282
    );

    lv_obj_set_y(
        ui_GcashPaybtn,
        185
    );

    lv_obj_set_align(
        ui_GcashPaybtn,
        LV_ALIGN_CENTER
    );

    lv_obj_add_flag(
        ui_GcashPaybtn,
        LV_OBJ_FLAG_SCROLL_ON_FOCUS
    );

    lv_obj_clear_flag(
        ui_GcashPaybtn,
        LV_OBJ_FLAG_SCROLLABLE
    );

    lv_obj_set_style_bg_color(
        ui_GcashPaybtn,
        lv_color_hex(0x00FF2C),
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_bg_opa(
        ui_GcashPaybtn,
        255,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );


    // ========================================================
    // PAY LABEL
    // ========================================================

    ui_paylbl =
        lv_label_create(ui_GcashPaybtn);

    lv_obj_set_width(
        ui_paylbl,
        LV_SIZE_CONTENT
    );

    lv_obj_set_height(
        ui_paylbl,
        LV_SIZE_CONTENT
    );

    lv_obj_set_x(
        ui_paylbl,
        -1
    );

    lv_obj_set_y(
        ui_paylbl,
        -2
    );

    lv_obj_set_align(
        ui_paylbl,
        LV_ALIGN_CENTER
    );

    lv_label_set_text(
        ui_paylbl,
        "Pay"
    );

    lv_obj_set_style_text_color(
        ui_paylbl,
        lv_color_hex(0xFFFFFF),
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_opa(
        ui_paylbl,
        255,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_font(
        ui_paylbl,
        &lv_font_montserrat_20,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_transform_zoom(
        ui_paylbl,
        256,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );


    // ========================================================
    // INSTRUCTION
    // ========================================================

    ui_Label6 =
        lv_label_create(ui_GcashPaymentScreen);

    lv_obj_set_width(
        ui_Label6,
        LV_SIZE_CONTENT
    );

    lv_obj_set_height(
        ui_Label6,
        LV_SIZE_CONTENT
    );

    lv_obj_set_x(
        ui_Label6,
        6
    );

    lv_obj_set_y(
        ui_Label6,
        57
    );

    lv_obj_set_align(
        ui_Label6,
        LV_ALIGN_CENTER
    );

    lv_label_set_text(
        ui_Label6,
        "Click \"Pay\" to proceed"
    );

    lv_obj_set_style_text_color(
        ui_Label6,
        lv_color_hex(0xFFFFFF),
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_opa(
        ui_Label6,
        255,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_font(
        ui_Label6,
        &lv_font_montserrat_20,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_transform_zoom(
        ui_Label6,
        256,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );


    // ========================================================
    // EVENT REGISTRATION
    // ========================================================

    // BACK BUTTON
    lv_obj_add_event_cb(
        ui_gcashbackbtn,
        ui_event_gcashbackbtn,
        LV_EVENT_CLICKED,
        NULL
    );


    // AMOUNT BUTTONS
    lv_obj_add_event_cb(
        ui_amount10cb,
        ui_event_amount10cb,
        LV_EVENT_CLICKED,
        NULL
    );

    lv_obj_add_event_cb(
        ui_amount20cb,
        ui_event_amount20cb,
        LV_EVENT_CLICKED,
        NULL
    );

    lv_obj_add_event_cb(
        ui_amount30cb,
        ui_event_amount30cb,
        LV_EVENT_CLICKED,
        NULL
    );


    // PAY BUTTON
    lv_obj_add_event_cb(
        ui_GcashPaybtn,
        ui_event_GcashPaybtn,
        LV_EVENT_CLICKED,
        NULL
    );
}


// ============================================================
// DESTROY
// ============================================================

void ui_GcashPaymentScreen_screen_destroy(void)
{
    if(ui_GcashPaymentScreen)
        lv_obj_del(ui_GcashPaymentScreen);

    ui_GcashPaymentScreen = NULL;
    ui_gcashbackbtn = NULL;
    ui_gacshbackbtn = NULL;
    ui_gcashlbl1 = NULL;
    ui_Container7 = NULL;
    ui_AmountoPaylbl = NULL;
    ui_Container6 = NULL;
    ui_amount10cb = NULL;
    ui_amount20cb = NULL;
    ui_amount30cb = NULL;
    ui_Container8 = NULL;
    ui_GcashCurrentCreditlbl = NULL;
    ui_GcashCValCreditlbl = NULL;
    ui_GcashPaybtn = NULL;
    ui_paylbl = NULL;
    ui_Label6 = NULL;

    gcashSelectedAmount = 0;
}

