// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Carwash_UI_LCD
#include "carwash_logic.h"
#include "ui.h"

lv_obj_t * ui_MainScreen = NULL;
lv_obj_t * ui_SCSlbl = NULL;
lv_obj_t * ui_usercontainer = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_UserCreditlbl1 = NULL;
lv_obj_t * ui_UserCreditlbl = NULL;
lv_obj_t * ui_UserCreditlbl2 = NULL;
lv_obj_t * ui_Container13 = NULL;
lv_obj_t * ui_waterquallbl2 = NULL;
lv_obj_t * ui_waterqualstat2 = NULL;
lv_obj_t * ui_Wifilbl2 = NULL;
lv_obj_t * ui_Wifistat2 = NULL;
lv_obj_t * ui_wifistatind = NULL;
lv_obj_t * ui_waterqualind = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_addtimecoinbtn = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_addtimegcashbtn = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_waterbtn = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_waterstatus = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_soapbtn = NULL;
lv_obj_t * ui_soaplogo = NULL;
lv_obj_t * ui_labelll = NULL;
lv_obj_t * ui_soapstatus = NULL;
lv_obj_t * ui_blowerbtn = NULL;
lv_obj_t * ui_blowerlogo = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_blowerstatus = NULL;
lv_obj_t * ui_faucetbtn = NULL;
lv_obj_t * ui_waterlogo1 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_faucetstatus = NULL;
lv_obj_t * ui_Label4 = NULL;
// event funtions
void ui_event_addtimecoinbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        addcoin_clicked(e);
    }
}

void ui_event_addtimegcashbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        addgcash_clicked(e);
    }
}

void ui_event_waterbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        water_clicked(e);
    }
}

void ui_event_soapbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        soap_clicked(e);
    }
}

void ui_event_blowerbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        blower_clicked(e);
    }
}

void ui_event_faucetbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        faucet_clicked(e);
    }
}

// build funtions

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SCSlbl = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_SCSlbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SCSlbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SCSlbl, -42);
    lv_obj_set_y(ui_SCSlbl, -218);
    lv_obj_set_align(ui_SCSlbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SCSlbl, "SMART CARWASH SYSTEM");
    lv_obj_set_style_text_color(ui_SCSlbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SCSlbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_SCSlbl, 400, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_usercontainer = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_usercontainer);
    lv_obj_set_width(ui_usercontainer, 551);
    lv_obj_set_height(ui_usercontainer, 192);
    lv_obj_set_x(ui_usercontainer, -183);
    lv_obj_set_y(ui_usercontainer, -116);
    lv_obj_set_align(ui_usercontainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_usercontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_usercontainer);
    lv_obj_set_width(ui_Panel1, 396);
    lv_obj_set_height(ui_Panel1, 102);
    lv_obj_set_x(ui_Panel1, 1);
    lv_obj_set_y(ui_Panel1, -11);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UserCreditlbl1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_UserCreditlbl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UserCreditlbl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UserCreditlbl1, -82);
    lv_obj_set_y(ui_UserCreditlbl1, -30);
    lv_obj_set_align(ui_UserCreditlbl1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UserCreditlbl1, "P 0.00");
    lv_obj_set_style_text_color(ui_UserCreditlbl1, lv_color_hex(0x00FF2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_UserCreditlbl1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_UserCreditlbl1, 1200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UserCreditlbl = lv_label_create(ui_usercontainer);
    lv_obj_set_width(ui_UserCreditlbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UserCreditlbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UserCreditlbl, 4);
    lv_obj_set_y(ui_UserCreditlbl, -61);
    lv_obj_set_align(ui_UserCreditlbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UserCreditlbl, "CURRENT CREDIT");
    lv_obj_set_style_text_color(ui_UserCreditlbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_UserCreditlbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_UserCreditlbl, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_UserCreditlbl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_UserCreditlbl, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UserCreditlbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UserCreditlbl2 = lv_label_create(ui_usercontainer);
    lv_obj_set_width(ui_UserCreditlbl2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UserCreditlbl2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UserCreditlbl2, 4);
    lv_obj_set_y(ui_UserCreditlbl2, -61);
    lv_obj_set_align(ui_UserCreditlbl2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UserCreditlbl2, "CURRENT CREDIT");
    lv_obj_set_style_text_color(ui_UserCreditlbl2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_UserCreditlbl2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_UserCreditlbl2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_UserCreditlbl2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_UserCreditlbl2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UserCreditlbl2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container13 = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_width(ui_Container13, 769);
    lv_obj_set_height(ui_Container13, 21);
    lv_obj_set_x(ui_Container13, 2);
    lv_obj_set_y(ui_Container13, 219);
    lv_obj_set_align(ui_Container13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_waterquallbl2 = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_waterquallbl2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_waterquallbl2, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_x(ui_waterquallbl2, -330);
    lv_obj_set_y(ui_waterquallbl2, 4);
    lv_obj_set_align(ui_waterquallbl2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_waterquallbl2, "Water quality:");
    lv_obj_set_style_text_color(ui_waterquallbl2, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_waterquallbl2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_waterqualstat2 = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_waterqualstat2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_waterqualstat2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_waterqualstat2, -214);
    lv_obj_set_y(ui_waterqualstat2, 4);
    lv_obj_set_align(ui_waterqualstat2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_waterqualstat2, "EXCELLENT");
    lv_obj_set_style_text_color(ui_waterqualstat2, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_waterqualstat2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wifilbl2 = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_Wifilbl2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifilbl2, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_x(ui_Wifilbl2, 248);
    lv_obj_set_y(ui_Wifilbl2, 4);
    lv_obj_set_align(ui_Wifilbl2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Wifilbl2, "WiFi:");
    lv_obj_set_style_text_color(ui_Wifilbl2, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Wifilbl2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wifistat2 = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_Wifistat2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifistat2, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_x(ui_Wifistat2, 338);
    lv_obj_set_y(ui_Wifistat2, 4);
    lv_obj_set_align(ui_Wifistat2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Wifistat2, "CONNECTED");
    lv_obj_set_style_text_color(ui_Wifistat2, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Wifistat2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifistatind = lv_obj_create(ui_Container13);
    lv_obj_set_width(ui_wifistatind, 19);
    lv_obj_set_height(ui_wifistatind, 14);
    lv_obj_set_x(ui_wifistatind, 279);
    lv_obj_set_y(ui_wifistatind, 3);
    lv_obj_set_align(ui_wifistatind, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_wifistatind, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wifistatind, lv_color_hex(0x0DFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifistatind, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_waterqualind = lv_obj_create(ui_Container13);
    lv_obj_set_width(ui_waterqualind, 19);
    lv_obj_set_height(ui_waterqualind, 14);
    lv_obj_set_x(ui_waterqualind, -266);
    lv_obj_set_y(ui_waterqualind, 4);
    lv_obj_set_align(ui_waterqualind, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_waterqualind, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_waterqualind, lv_color_hex(0x0DFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_waterqualind, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_Panel3, 245);
    lv_obj_set_height(ui_Panel3, 247);
    lv_obj_set_x(ui_Panel3, 221);
    lv_obj_set_y(ui_Panel3, -54);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 226);
    lv_obj_set_y(ui_Label1, -177);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "ADD TIME");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label1, lv_color_hex(0x0A0A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_Label1, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_addtimecoinbtn = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_addtimecoinbtn, 190);
    lv_obj_set_height(ui_addtimecoinbtn, 83);
    lv_obj_set_x(ui_addtimecoinbtn, 225);
    lv_obj_set_y(ui_addtimecoinbtn, -106);
    lv_obj_set_align(ui_addtimecoinbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_addtimecoinbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_addtimecoinbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_addtimecoinbtn, lv_color_hex(0xFFD600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_addtimecoinbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_addtimecoinbtn);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 23);
    lv_obj_set_y(ui_Label3, -1);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "COIN");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_Label3, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_addtimecoinbtn);
    lv_img_set_src(ui_Image1, &ui_img_1834858727);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, -34);
    lv_obj_set_y(ui_Image1, -2);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 100);

    ui_addtimegcashbtn = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_addtimegcashbtn, 193);
    lv_obj_set_height(ui_addtimegcashbtn, 83);
    lv_obj_set_x(ui_addtimegcashbtn, 227);
    lv_obj_set_y(ui_addtimegcashbtn, 1);
    lv_obj_set_align(ui_addtimegcashbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_addtimegcashbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_addtimegcashbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_addtimegcashbtn, lv_color_hex(0x008DFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_addtimegcashbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_addtimegcashbtn);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 25);
    lv_obj_set_y(ui_Label5, 0);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "GCASH");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_Label5, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_addtimegcashbtn);
    lv_img_set_src(ui_Image2, &ui_img_346396786);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, -46);
    lv_obj_set_y(ui_Image2, -13);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 110);

    ui_waterbtn = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_waterbtn, 129);
    lv_obj_set_height(ui_waterbtn, 113);
    lv_obj_set_x(ui_waterbtn, -319);
    lv_obj_set_y(ui_waterbtn, -1);
    lv_obj_set_align(ui_waterbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_waterbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_waterbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_waterbtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_waterbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_waterbtn, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_waterbtn);
    lv_img_set_src(ui_Image4, &ui_img_water_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, -1);
    lv_obj_set_y(ui_Image4, -2);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 25);

    ui_waterstatus = lv_label_create(ui_waterbtn);
    lv_obj_set_width(ui_waterstatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_waterstatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_waterstatus, 1);
    lv_obj_set_y(ui_waterstatus, 38);
    lv_obj_set_align(ui_waterstatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_waterstatus, "Ready");
    lv_obj_set_style_text_color(ui_waterstatus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_waterstatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_waterstatus, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_waterstatus, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_waterbtn);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 0);
    lv_obj_set_y(ui_Label9, -41);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Water ");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_Label9, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_soapbtn = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_soapbtn, 129);
    lv_obj_set_height(ui_soapbtn, 113);
    lv_obj_set_x(ui_soapbtn, -174);
    lv_obj_set_y(ui_soapbtn, -3);
    lv_obj_set_align(ui_soapbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_soapbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_soapbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_soapbtn, lv_color_hex(0x2400FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_soapbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_soaplogo = lv_img_create(ui_soapbtn);
    lv_img_set_src(ui_soaplogo, &ui_img_2086251881);
    lv_obj_set_width(ui_soaplogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_soaplogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_soaplogo, 1);
    lv_obj_set_y(ui_soaplogo, 0);
    lv_obj_set_align(ui_soaplogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_soaplogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_soaplogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_soaplogo, 90);

    ui_labelll = lv_label_create(ui_soapbtn);
    lv_obj_set_width(ui_labelll, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelll, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelll, 1);
    lv_obj_set_y(ui_labelll, -42);
    lv_obj_set_align(ui_labelll, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelll, "Soap");
    lv_obj_set_style_text_color(ui_labelll, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelll, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelll, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_labelll, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_soapstatus = lv_label_create(ui_soapbtn);
    lv_obj_set_width(ui_soapstatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_soapstatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_soapstatus, 0);
    lv_obj_set_y(ui_soapstatus, 39);
    lv_obj_set_align(ui_soapstatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_soapstatus, "Ready");
    lv_obj_set_style_text_color(ui_soapstatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_soapstatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_soapstatus, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_soapstatus, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_blowerbtn = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_blowerbtn, 129);
    lv_obj_set_height(ui_blowerbtn, 113);
    lv_obj_set_x(ui_blowerbtn, -318);
    lv_obj_set_y(ui_blowerbtn, 132);
    lv_obj_set_align(ui_blowerbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_blowerbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_blowerbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_blowerbtn, lv_color_hex(0xBDFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_blowerbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_blowerlogo = lv_img_create(ui_blowerbtn);
    lv_img_set_src(ui_blowerlogo, &ui_img_246023399);
    lv_obj_set_width(ui_blowerlogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_blowerlogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_blowerlogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_blowerlogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_blowerlogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_blowerlogo, 100);

    ui_Label13 = lv_label_create(ui_blowerbtn);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 0);
    lv_obj_set_y(ui_Label13, -42);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Blower");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_Label13, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_blowerstatus = lv_label_create(ui_blowerbtn);
    lv_obj_set_width(ui_blowerstatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_blowerstatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_blowerstatus, 0);
    lv_obj_set_y(ui_blowerstatus, 39);
    lv_obj_set_align(ui_blowerstatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_blowerstatus, "Ready");
    lv_obj_set_style_text_color(ui_blowerstatus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_blowerstatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_blowerstatus, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_blowerstatus, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_faucetbtn = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_faucetbtn, 129);
    lv_obj_set_height(ui_faucetbtn, 113);
    lv_obj_set_x(ui_faucetbtn, -173);
    lv_obj_set_y(ui_faucetbtn, 132);
    lv_obj_set_align(ui_faucetbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_faucetbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_faucetbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_faucetbtn, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_faucetbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_waterlogo1 = lv_img_create(ui_faucetbtn);
    lv_img_set_src(ui_waterlogo1, &ui_img_1364712669);
    lv_obj_set_width(ui_waterlogo1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_waterlogo1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_waterlogo1, 0);
    lv_obj_set_y(ui_waterlogo1, 3);
    lv_obj_set_align(ui_waterlogo1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_waterlogo1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_waterlogo1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_waterlogo1, 100);

    ui_Label15 = lv_label_create(ui_faucetbtn);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -2);
    lv_obj_set_y(ui_Label15, -42);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Faucet");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_Label15, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_faucetstatus = lv_label_create(ui_faucetbtn);
    lv_obj_set_width(ui_faucetstatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_faucetstatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_faucetstatus, 1);
    lv_obj_set_y(ui_faucetstatus, 40);
    lv_obj_set_align(ui_faucetstatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_faucetstatus, "Ready");
    lv_obj_set_style_text_color(ui_faucetstatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_faucetstatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_faucetstatus, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_faucetstatus, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 150);
    lv_obj_set_y(ui_Label4, 136);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Choose a service, then press \"START\" to begin.");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_Label4, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_addtimecoinbtn, ui_event_addtimecoinbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_addtimegcashbtn, ui_event_addtimegcashbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_waterbtn, ui_event_waterbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_soapbtn, ui_event_soapbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_blowerbtn, ui_event_blowerbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_faucetbtn, ui_event_faucetbtn, LV_EVENT_ALL, NULL);

}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_SCSlbl = NULL;
    ui_usercontainer = NULL;
    ui_Panel1 = NULL;
    ui_UserCreditlbl1 = NULL;
    ui_UserCreditlbl = NULL;
    ui_UserCreditlbl2 = NULL;
    ui_Container13 = NULL;
    ui_waterquallbl2 = NULL;
    ui_waterqualstat2 = NULL;
    ui_Wifilbl2 = NULL;
    ui_Wifistat2 = NULL;
    ui_wifistatind = NULL;
    ui_waterqualind = NULL;
    ui_Panel3 = NULL;
    ui_Label1 = NULL;
    ui_addtimecoinbtn = NULL;
    ui_Label3 = NULL;
    ui_Image1 = NULL;
    ui_addtimegcashbtn = NULL;
    ui_Label5 = NULL;
    ui_Image2 = NULL;
    ui_waterbtn = NULL;
    ui_Image4 = NULL;
    ui_waterstatus = NULL;
    ui_Label9 = NULL;
    ui_soapbtn = NULL;
    ui_soaplogo = NULL;
    ui_labelll = NULL;
    ui_soapstatus = NULL;
    ui_blowerbtn = NULL;
    ui_blowerlogo = NULL;
    ui_Label13 = NULL;
    ui_blowerstatus = NULL;
    ui_faucetbtn = NULL;
    ui_waterlogo1 = NULL;
    ui_Label15 = NULL;
    ui_faucetstatus = NULL;
    ui_Label4 = NULL;

}
