// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Carwash_UI_LCD

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_SCSlbl;
extern lv_obj_t * ui_usercontainer;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_UserCreditlbl1;
extern lv_obj_t * ui_UserCreditlbl;
extern lv_obj_t * ui_UserCreditlbl2;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_waterquallbl2;
extern lv_obj_t * ui_waterqualstat2;
extern lv_obj_t * ui_Wifilbl2;
extern lv_obj_t * ui_Wifistat2;
extern lv_obj_t * ui_wifistatind;
extern lv_obj_t * ui_waterqualind;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label1;
extern void ui_event_addtimecoinbtn(lv_event_t * e);
extern lv_obj_t * ui_addtimecoinbtn;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Image1;
extern void ui_event_addtimegcashbtn(lv_event_t * e);
extern lv_obj_t * ui_addtimegcashbtn;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Image2;
extern void ui_event_waterbtn(lv_event_t * e);
extern lv_obj_t * ui_waterbtn;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_waterstatus;
extern lv_obj_t * ui_Label9;
extern void ui_event_soapbtn(lv_event_t * e);
extern lv_obj_t * ui_soapbtn;
extern lv_obj_t * ui_soaplogo;
extern lv_obj_t * ui_labelll;
extern lv_obj_t * ui_soapstatus;
extern void ui_event_blowerbtn(lv_event_t * e);
extern lv_obj_t * ui_blowerbtn;
extern lv_obj_t * ui_blowerlogo;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_blowerstatus;
extern void ui_event_faucetbtn(lv_event_t * e);
extern lv_obj_t * ui_faucetbtn;
extern lv_obj_t * ui_waterlogo1;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_faucetstatus;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

