// This file was generated by SquareLine Studio
// Modified for Carwash project
//
// SELECT PAYMENT PAGE
// -----------------------------------------
// COIN  -> existing coin_clicked()
// GCASH -> existing gcash_clicked()
// BACK  -> existing back_to_home()
//
// GCash amount selection will happen on the
// GCash payment side, NOT on this page.
//
// Fixed GCash amounts:
// PHP 10
// PHP 20
// PHP 30

#include "ui.h"
#include "ui_SelectPaymentpage.h"
#include "ui_helpers.h"


// ============================================================
// EXISTING CALLBACKS
// ============================================================
//
// These functions are supplied by the main carwash project.
// We keep them instead of creating duplicate navigation code.
//

extern void gcash_clicked(lv_event_t * e);
extern void coin_clicked(lv_event_t * e);
extern void back_to_home(lv_event_t * e);


// ============================================================
// UI OBJECTS
// ============================================================

lv_obj_t * ui_SelectPaymentpage = NULL;
lv_obj_t * ui_PaymentMethodlbl = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_Coinlbl = NULL;
lv_obj_t * ui_Gcashlbl = NULL;
lv_obj_t * ui_gcashbtn = NULL;
lv_obj_t * ui_gcashimg = NULL;
lv_obj_t * ui_coinbtn = NULL;
lv_obj_t * ui_coinimg = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_CurrentCreditlbl = NULL;
lv_obj_t * ui_CreditVallbl = NULL;
lv_obj_t * ui_backbtn2 = NULL;
lv_obj_t * ui_backlbl2 = NULL;


// ============================================================
// GCASH SELECTED AMOUNT
// ============================================================
//
// This variable is NOT used on the Select Payment page yet.
// The GCash payment screen can use it later for:
// PHP 10 / PHP 20 / PHP 30
//

volatile uint16_t selectedPaymentAmount = 0;


// ============================================================
// GCASH BUTTON EVENT
// ============================================================

void ui_event_gcashbtn(lv_event_t * e)
{
    if (e == NULL)
        return;

    if (lv_event_get_code(e) == LV_EVENT_CLICKED)
    {
        /*
         * IMPORTANT:
         *
         * Only the GCASH button enters the GCash payment flow.
         *
         * The amount selection PHP 10 / PHP 20 / PHP 30
         * belongs on the GCash payment side.
         */
        gcash_clicked(e);
    }
}


// ============================================================
// COIN BUTTON EVENT
// ============================================================

void ui_event_coinbtn(lv_event_t * e)
{
    if (e == NULL)
        return;

    if (lv_event_get_code(e) == LV_EVENT_CLICKED)
    {
        /*
         * Coin payment remains completely separate
         * from the GCash payment flow.
         */
        coin_clicked(e);
    }
}


// ============================================================
// BACK BUTTON EVENT
// ============================================================

void ui_event_backbtn2(lv_event_t * e)
{
    if (e == NULL)
        return;

    if (lv_event_get_code(e) == LV_EVENT_CLICKED)
    {
        /*
         * Clear any previous GCash amount
         * when leaving the payment selection page.
         */
        selectedPaymentAmount = 0;

        back_to_home(e);
    }
}


// ============================================================
// SCREEN INIT
// ============================================================

void ui_SelectPaymentpage_screen_init(void)
{
    // --------------------------------------------------------
    // SCREEN
    // --------------------------------------------------------

    ui_SelectPaymentpage =
        lv_obj_create(NULL);

    lv_obj_clear_flag(
        ui_SelectPaymentpage,
        LV_OBJ_FLAG_SCROLLABLE
    );

    lv_obj_set_style_bg_color(
        ui_SelectPaymentpage,
        lv_color_hex(0x000000),
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_bg_opa(
        ui_SelectPaymentpage,
        255,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );


    // --------------------------------------------------------
    // TITLE
    // --------------------------------------------------------

    ui_PaymentMethodlbl =
        lv_label_create(ui_SelectPaymentpage);

    lv_obj_set_width(
        ui_PaymentMethodlbl,
        LV_SIZE_CONTENT
    );

    lv_obj_set_height(
        ui_PaymentMethodlbl,
        LV_SIZE_CONTENT
    );

    lv_obj_set_x(
        ui_PaymentMethodlbl,
        -1
    );

    lv_obj_set_y(
        ui_PaymentMethodlbl,
        -213
    );

    lv_obj_set_align(
        ui_PaymentMethodlbl,
        LV_ALIGN_CENTER
    );

    lv_label_set_text(
        ui_PaymentMethodlbl,
        "Select Payment Method"
    );

    lv_obj_set_style_text_color(
        ui_PaymentMethodlbl,
        lv_color_hex(0xFFFFFF),
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_opa(
        ui_PaymentMethodlbl,
        255,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_font(
        ui_PaymentMethodlbl,
        &lv_font_montserrat_20,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_transform_zoom(
        ui_PaymentMethodlbl,
        256,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );


    // --------------------------------------------------------
    // PAYMENT BUTTON CONTAINER
    // --------------------------------------------------------

    ui_Container3 =
        lv_obj_create(ui_SelectPaymentpage);

    lv_obj_remove_style_all(
        ui_Container3
    );

    lv_obj_set_width(
        ui_Container3,
        735
    );

    lv_obj_set_height(
        ui_Container3,
        233
    );

    lv_obj_set_x(
        ui_Container3,
        8
    );

    lv_obj_set_y(
        ui_Container3,
        -37
    );

    lv_obj_set_align(
        ui_Container3,
        LV_ALIGN_CENTER
    );

    lv_obj_clear_flag(
        ui_Container3,
        LV_OBJ_FLAG_CLICKABLE |
        LV_OBJ_FLAG_SCROLLABLE
    );


    // ========================================================
    // COIN LABEL
    // ========================================================

    ui_Coinlbl =
        lv_label_create(ui_Container3);

    lv_obj_set_width(
        ui_Coinlbl,
        LV_SIZE_CONTENT
    );

    lv_obj_set_height(
        ui_Coinlbl,
        LV_SIZE_CONTENT
    );

    lv_obj_set_x(
        ui_Coinlbl,
        -156
    );

    lv_obj_set_y(
        ui_Coinlbl,
        -83
    );

    lv_obj_set_align(
        ui_Coinlbl,
        LV_ALIGN_CENTER
    );

    lv_label_set_text(
        ui_Coinlbl,
        "Coin"
    );

    lv_obj_set_style_text_color(
        ui_Coinlbl,
        lv_color_hex(0xFFFAFF),
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_opa(
        ui_Coinlbl,
        255,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_font(
        ui_Coinlbl,
        &lv_font_montserrat_18,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_transform_zoom(
        ui_Coinlbl,
        256,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );


    // ========================================================
    // GCASH LABEL
    // ========================================================

    ui_Gcashlbl =
        lv_label_create(ui_Container3);

    lv_obj_set_width(
        ui_Gcashlbl,
        LV_SIZE_CONTENT
    );

    lv_obj_set_height(
        ui_Gcashlbl,
        LV_SIZE_CONTENT
    );

    lv_obj_set_x(
        ui_Gcashlbl,
        154
    );

    lv_obj_set_y(
        ui_Gcashlbl,
        -80
    );

    lv_obj_set_align(
        ui_Gcashlbl,
        LV_ALIGN_CENTER
    );

    lv_label_set_text(
        ui_Gcashlbl,
        "Gcash"
    );

    lv_obj_set_style_text_color(
        ui_Gcashlbl,
        lv_color_hex(0xFFFAFF),
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_opa(
        ui_Gcashlbl,
        255,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_font(
        ui_Gcashlbl,
        &lv_font_montserrat_18,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_transform_zoom(
        ui_Gcashlbl,
        256,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );


    // ========================================================
    // GCASH BUTTON
    // ========================================================

    ui_gcashbtn =
        lv_btn_create(ui_Container3);

    lv_obj_set_width(
        ui_gcashbtn,
        214
    );

    lv_obj_set_height(
        ui_gcashbtn,
        165
    );

    lv_obj_set_x(
        ui_gcashbtn,
        154
    );

    lv_obj_set_y(
        ui_gcashbtn,
        15
    );

    lv_obj_set_align(
        ui_gcashbtn,
        LV_ALIGN_CENTER
    );

    lv_obj_add_flag(
        ui_gcashbtn,
        LV_OBJ_FLAG_SCROLL_ON_FOCUS
    );

    lv_obj_clear_flag(
        ui_gcashbtn,
        LV_OBJ_FLAG_SCROLLABLE
    );

    lv_obj_set_style_bg_color(
        ui_gcashbtn,
        lv_color_hex(0x008DFF),
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_bg_opa(
        ui_gcashbtn,
        255,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );


    // --------------------------------------------------------
    // GCASH IMAGE
    // --------------------------------------------------------

    ui_gcashimg =
        lv_img_create(ui_gcashbtn);

    lv_img_set_src(
        ui_gcashimg,
        &ui_img_346396786
    );

    lv_obj_set_width(
        ui_gcashimg,
        LV_SIZE_CONTENT
    );

    lv_obj_set_height(
        ui_gcashimg,
        LV_SIZE_CONTENT
    );

    lv_obj_set_x(
        ui_gcashimg,
        4
    );

    lv_obj_set_y(
        ui_gcashimg,
        -23
    );

    lv_obj_set_align(
        ui_gcashimg,
        LV_ALIGN_CENTER
    );

    lv_obj_add_flag(
        ui_gcashimg,
        LV_OBJ_FLAG_ADV_HITTEST
    );

    lv_obj_clear_flag(
        ui_gcashimg,
        LV_OBJ_FLAG_SCROLLABLE
    );

    lv_img_set_zoom(
        ui_gcashimg,
        250
    );


    // ========================================================
    // COIN BUTTON
    // ========================================================

    ui_coinbtn =
        lv_btn_create(ui_Container3);

    lv_obj_set_width(
        ui_coinbtn,
        214
    );

    lv_obj_set_height(
        ui_coinbtn,
        165
    );

    lv_obj_set_x(
        ui_coinbtn,
        -155
    );

    lv_obj_set_y(
        ui_coinbtn,
        14
    );

    lv_obj_set_align(
        ui_coinbtn,
        LV_ALIGN_CENTER
    );

    lv_obj_add_flag(
        ui_coinbtn,
        LV_OBJ_FLAG_SCROLL_ON_FOCUS
    );

    lv_obj_clear_flag(
        ui_coinbtn,
        LV_OBJ_FLAG_SCROLLABLE
    );

    lv_obj_set_style_bg_color(
        ui_coinbtn,
        lv_color_hex(0xFFD700),
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_bg_opa(
        ui_coinbtn,
        255,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );


    // --------------------------------------------------------
    // COIN IMAGE
    // --------------------------------------------------------

    ui_coinimg =
        lv_img_create(ui_coinbtn);

    lv_img_set_src(
        ui_coinimg,
        &ui_img_1834858727
    );

    lv_obj_set_width(
        ui_coinimg,
        LV_SIZE_CONTENT
    );

    lv_obj_set_height(
        ui_coinimg,
        LV_SIZE_CONTENT
    );

    lv_obj_set_x(
        ui_coinimg,
        -5
    );

    lv_obj_set_y(
        ui_coinimg,
        4
    );

    lv_obj_set_align(
        ui_coinimg,
        LV_ALIGN_CENTER
    );

    lv_obj_add_flag(
        ui_coinimg,
        LV_OBJ_FLAG_ADV_HITTEST
    );

    lv_obj_clear_flag(
        ui_coinimg,
        LV_OBJ_FLAG_SCROLLABLE
    );

    lv_img_set_zoom(
        ui_coinimg,
        200
    );


    // ========================================================
    // CURRENT CREDIT CONTAINER
    // ========================================================

    ui_Container4 =
        lv_obj_create(ui_SelectPaymentpage);

    lv_obj_remove_style_all(
        ui_Container4
    );

    lv_obj_set_width(
        ui_Container4,
        413
    );

    lv_obj_set_height(
        ui_Container4,
        121
    );

    lv_obj_set_x(
        ui_Container4,
        20
    );

    lv_obj_set_y(
        ui_Container4,
        123
    );

    lv_obj_set_align(
        ui_Container4,
        LV_ALIGN_CENTER
    );

    lv_obj_clear_flag(
        ui_Container4,
        LV_OBJ_FLAG_CLICKABLE |
        LV_OBJ_FLAG_SCROLLABLE
    );


    // ========================================================
    // CURRENT CREDIT LABEL
    // ========================================================

    ui_CurrentCreditlbl =
        lv_label_create(ui_Container4);

    lv_obj_set_width(
        ui_CurrentCreditlbl,
        LV_SIZE_CONTENT
    );

    lv_obj_set_height(
        ui_CurrentCreditlbl,
        LV_SIZE_CONTENT
    );

    lv_obj_set_x(
        ui_CurrentCreditlbl,
        -12
    );

    lv_obj_set_y(
        ui_CurrentCreditlbl,
        -31
    );

    lv_obj_set_align(
        ui_CurrentCreditlbl,
        LV_ALIGN_CENTER
    );

    lv_label_set_text(
        ui_CurrentCreditlbl,
        "Current Credit:"
    );

    lv_obj_set_style_text_color(
        ui_CurrentCreditlbl,
        lv_color_hex(0xFDFBFB),
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_opa(
        ui_CurrentCreditlbl,
        255,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_font(
        ui_CurrentCreditlbl,
        &lv_font_montserrat_18,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_transform_zoom(
        ui_CurrentCreditlbl,
        256,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );


    // ========================================================
    // CREDIT VALUE
    // ========================================================

    ui_CreditVallbl =
        lv_label_create(ui_Container4);

    lv_obj_set_width(
        ui_CreditVallbl,
        LV_SIZE_CONTENT
    );

    lv_obj_set_height(
        ui_CreditVallbl,
        LV_SIZE_CONTENT
    );

    lv_obj_set_x(
        ui_CreditVallbl,
        -15
    );

    lv_obj_set_y(
        ui_CreditVallbl,
        10
    );

    lv_obj_set_align(
        ui_CreditVallbl,
        LV_ALIGN_CENTER
    );

    lv_label_set_text(
        ui_CreditVallbl,
        "P0.00"
    );

    lv_obj_set_style_text_color(
        ui_CreditVallbl,
        lv_color_hex(0xFDFBFB),
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_opa(
        ui_CreditVallbl,
        255,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_letter_space(
        ui_CreditVallbl,
        5,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_line_space(
        ui_CreditVallbl,
        3,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_font(
        ui_CreditVallbl,
        &lv_font_montserrat_28,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_transform_zoom(
        ui_CreditVallbl,
        256,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );


    // ========================================================
    // BACK BUTTON
    // ========================================================

    ui_backbtn2 =
        lv_btn_create(ui_SelectPaymentpage);

    lv_obj_set_width(
        ui_backbtn2,
        82
    );

    lv_obj_set_height(
        ui_backbtn2,
        38
    );

    lv_obj_set_x(
        ui_backbtn2,
        -348
    );

    lv_obj_set_y(
        ui_backbtn2,
        -209
    );

    lv_obj_set_align(
        ui_backbtn2,
        LV_ALIGN_CENTER
    );

    lv_obj_add_flag(
        ui_backbtn2,
        LV_OBJ_FLAG_SCROLL_ON_FOCUS
    );

    lv_obj_clear_flag(
        ui_backbtn2,
        LV_OBJ_FLAG_SCROLLABLE
    );

    lv_obj_set_style_bg_color(
        ui_backbtn2,
        lv_color_hex(0xFF0000),
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_bg_opa(
        ui_backbtn2,
        255,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );


    // --------------------------------------------------------
    // BACK LABEL
    // --------------------------------------------------------

    ui_backlbl2 =
        lv_label_create(ui_backbtn2);

    lv_obj_set_width(
        ui_backlbl2,
        LV_SIZE_CONTENT
    );

    lv_obj_set_height(
        ui_backlbl2,
        LV_SIZE_CONTENT
    );

    lv_obj_set_x(
        ui_backlbl2,
        -2
    );

    lv_obj_set_y(
        ui_backlbl2,
        0
    );

    lv_obj_set_align(
        ui_backlbl2,
        LV_ALIGN_CENTER
    );

    lv_label_set_text(
        ui_backlbl2,
        "Back"
    );

    lv_obj_set_style_text_color(
        ui_backlbl2,
        lv_color_hex(0xFFFFFF),
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    lv_obj_set_style_text_opa(
        ui_backlbl2,
        255,
        LV_PART_MAIN | LV_STATE_DEFAULT
    );


    // ========================================================
    // EVENTS
    // ========================================================
    //
    // Use LV_EVENT_CLICKED only.
    // This avoids unnecessary event processing.
    //

    lv_obj_add_event_cb(
        ui_gcashbtn,
        ui_event_gcashbtn,
        LV_EVENT_CLICKED,
        NULL
    );

    lv_obj_add_event_cb(
        ui_coinbtn,
        ui_event_coinbtn,
        LV_EVENT_CLICKED,
        NULL
    );

    lv_obj_add_event_cb(
        ui_backbtn2,
        ui_event_backbtn2,
        LV_EVENT_CLICKED,
        NULL
    );


    // Start with no GCash amount selected.
    selectedPaymentAmount = 0;
}


// ============================================================
// SCREEN DESTROY
// ============================================================

void ui_SelectPaymentpage_screen_destroy(void)
{
    if (ui_SelectPaymentpage)
    {
        lv_obj_del(
            ui_SelectPaymentpage
        );
    }

    ui_SelectPaymentpage = NULL;

    ui_PaymentMethodlbl = NULL;
    ui_Container3 = NULL;

    ui_Coinlbl = NULL;
    ui_Gcashlbl = NULL;

    ui_gcashbtn = NULL;
    ui_gcashimg = NULL;

    ui_coinbtn = NULL;
    ui_coinimg = NULL;

    ui_Container4 = NULL;

    ui_CurrentCreditlbl = NULL;
    ui_CreditVallbl = NULL;

    ui_backbtn2 = NULL;
    ui_backlbl2 = NULL;

    selectedPaymentAmount = 0;
}