// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Carwash_UI_LCD

#ifndef UI_SELECTPAYMENTPAGE_H
#define UI_SELECTPAYMENTPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SelectPaymentpage
extern void ui_SelectPaymentpage_screen_init(void);
extern void ui_SelectPaymentpage_screen_destroy(void);
extern lv_obj_t * ui_SelectPaymentpage;
extern lv_obj_t * ui_PaymentMethodlbl;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Coinlbl;
extern lv_obj_t * ui_Gcashlbl;
extern void ui_event_gcashbtn(lv_event_t * e);
extern lv_obj_t * ui_gcashbtn;
extern lv_obj_t * ui_gcashimg;
extern void ui_event_coinbtn(lv_event_t * e);
extern lv_obj_t * ui_coinbtn;
extern lv_obj_t * ui_coinimg;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_CurrentCreditlbl;
extern lv_obj_t * ui_CreditVallbl;
extern void ui_event_backbtn2(lv_event_t * e);
extern lv_obj_t * ui_backbtn2;
extern lv_obj_t * ui_backlbl2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

