// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Carwash_UI_LCD

#ifndef UI_THANKYOUSCREEN_H
#define UI_THANKYOUSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_thankyouscreen
extern void ui_thankyouscreen_screen_init(void);
extern void ui_thankyouscreen_screen_destroy(void);
extern lv_obj_t * ui_thankyouscreen;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_exittimer;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

