// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Carwash_UI_LCD

#include "ui.h"

lv_obj_t * ui_thankyouscreen = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_exittimer = NULL;
// event funtions

// build funtions

void ui_thankyouscreen_screen_init(void)
{
    ui_thankyouscreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_thankyouscreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_thankyouscreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_thankyouscreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_thankyouscreen, lv_color_hex(0x00FF07), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_thankyouscreen, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_thankyouscreen, LV_BORDER_SIDE_BOTTOM, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_thankyouscreen, lv_color_hex(0x00FF24), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_thankyouscreen, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_thankyouscreen, 5, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_thankyouscreen, 5, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_thankyouscreen);
    lv_img_set_src(ui_Image3, &ui_img_898050187);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, 5);
    lv_obj_set_y(ui_Image3, -47);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 180);

    ui_Label7 = lv_label_create(ui_thankyouscreen);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 5);
    lv_obj_set_y(ui_Label7, -203);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Session Ended");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_Label7, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_thankyouscreen);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 3);
    lv_obj_set_y(ui_Label2, 152);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Returning in.....");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_Label2, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_exittimer = lv_label_create(ui_thankyouscreen);
    lv_obj_set_width(ui_exittimer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_exittimer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_exittimer, 98);
    lv_obj_set_y(ui_exittimer, 150);
    lv_obj_set_align(ui_exittimer, LV_ALIGN_CENTER);
    lv_label_set_text(ui_exittimer, "5");
    lv_obj_set_style_text_color(ui_exittimer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_exittimer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_exittimer, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_exittimer, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_thankyouscreen_screen_destroy(void)
{
    if(ui_thankyouscreen) lv_obj_del(ui_thankyouscreen);

    // NULL screen variables
    ui_thankyouscreen = NULL;
    ui_Image3 = NULL;
    ui_Label7 = NULL;
    ui_Label2 = NULL;
    ui_exittimer = NULL;

}
