// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Carwash_UI_LCD

#ifndef UI_WELCOMEPAGE_H
#define UI_WELCOMEPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_welcomepage
extern void ui_welcomepage_screen_init(void);
extern void ui_welcomepage_screen_destroy(void);
extern lv_obj_t * ui_welcomepage;
extern lv_obj_t * ui_waterqualind1;
extern void ui_event_Startbtn(lv_event_t * e);
extern lv_obj_t * ui_Startbtn;
extern lv_obj_t * ui_Startlbl;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_waterquallbl;
extern lv_obj_t * ui_waterqualstat;
extern lv_obj_t * ui_Wifilbl;
extern lv_obj_t * ui_Wifistat;
extern lv_obj_t * ui_waterqualpanel1;
extern void ui_event_CWlogo(lv_event_t * e);
extern lv_obj_t * ui_CWlogo;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_waterquallbl1;
extern lv_obj_t * ui_waterqualstat1;
extern lv_obj_t * ui_Wifilbl1;
extern lv_obj_t * ui_Wifistat1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Button1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

