// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Carwash_UI_LCD

#include "ui.h"

lv_obj_t * uic_Button1;
lv_obj_t * ui_welcomepage = NULL;
lv_obj_t * ui_waterqualind1 = NULL;
lv_obj_t * ui_Startbtn = NULL;
lv_obj_t * ui_Startlbl = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_waterquallbl = NULL;
lv_obj_t * ui_waterqualstat = NULL;
lv_obj_t * ui_Wifilbl = NULL;
lv_obj_t * ui_Wifistat = NULL;
lv_obj_t * ui_waterqualpanel1 = NULL;
lv_obj_t * ui_CWlogo = NULL;
lv_obj_t * ui_Container11 = NULL;
lv_obj_t * ui_waterquallbl1 = NULL;
lv_obj_t * ui_waterqualstat1 = NULL;
lv_obj_t * ui_Wifilbl1 = NULL;
lv_obj_t * ui_Wifistat1 = NULL;
// event funtions
void ui_event_Startbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        start_clicked(e);
    }
}

void ui_event_CWlogo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        admin_logo_clicked(e);
    }
}

// build funtions

void ui_welcomepage_screen_init(void)
{
    ui_welcomepage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_welcomepage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_welcomepage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_welcomepage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_waterqualind1 = lv_obj_create(ui_welcomepage);
    lv_obj_set_width(ui_waterqualind1, 19);
    lv_obj_set_height(ui_waterqualind1, 14);
    lv_obj_set_x(ui_waterqualind1, -265);
    lv_obj_set_y(ui_waterqualind1, 224);
    lv_obj_set_align(ui_waterqualind1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_waterqualind1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_waterqualind1, lv_color_hex(0x0DFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_waterqualind1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Startbtn = lv_btn_create(ui_welcomepage);
    lv_obj_set_width(ui_Startbtn, 203);
    lv_obj_set_height(ui_Startbtn, 76);
    lv_obj_set_x(ui_Startbtn, 12);
    lv_obj_set_y(ui_Startbtn, 164);
    lv_obj_set_align(ui_Startbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Startbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Startbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Startbtn, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Startbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Startlbl = lv_label_create(ui_Startbtn);
    lv_obj_set_width(ui_Startlbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Startlbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Startlbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Startlbl, "START");
    lv_obj_set_style_text_color(ui_Startlbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Startlbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Startlbl, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_Startlbl, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_welcomepage);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 769);
    lv_obj_set_height(ui_Container1, 21);
    lv_obj_set_x(ui_Container1, 2);
    lv_obj_set_y(ui_Container1, 219);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_waterquallbl = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_waterquallbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_waterquallbl, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_x(ui_waterquallbl, -330);
    lv_obj_set_y(ui_waterquallbl, 4);
    lv_obj_set_align(ui_waterquallbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_waterquallbl, "Water quality:");
    lv_obj_set_style_text_color(ui_waterquallbl, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_waterquallbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_waterqualstat = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_waterqualstat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_waterqualstat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_waterqualstat, -214);
    lv_obj_set_y(ui_waterqualstat, 4);
    lv_obj_set_align(ui_waterqualstat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_waterqualstat, "EXCELLENT");
    lv_obj_set_style_text_color(ui_waterqualstat, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_waterqualstat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wifilbl = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Wifilbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifilbl, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_x(ui_Wifilbl, 248);
    lv_obj_set_y(ui_Wifilbl, 4);
    lv_obj_set_align(ui_Wifilbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Wifilbl, "WiFi:");
    lv_obj_set_style_text_color(ui_Wifilbl, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Wifilbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wifistat = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Wifistat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifistat, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_x(ui_Wifistat, 338);
    lv_obj_set_y(ui_Wifistat, 4);
    lv_obj_set_align(ui_Wifistat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Wifistat, "CONNECTED");
    lv_obj_set_style_text_color(ui_Wifistat, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Wifistat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_waterqualpanel1 = lv_obj_create(ui_welcomepage);
    lv_obj_set_width(ui_waterqualpanel1, 19);
    lv_obj_set_height(ui_waterqualpanel1, 14);
    lv_obj_set_x(ui_waterqualpanel1, 280);
    lv_obj_set_y(ui_waterqualpanel1, 224);
    lv_obj_set_align(ui_waterqualpanel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_waterqualpanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_waterqualpanel1, lv_color_hex(0x0DFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_waterqualpanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CWlogo = lv_img_create(ui_welcomepage);
    lv_img_set_src(ui_CWlogo, &ui_img_logo_png);
    lv_obj_set_width(ui_CWlogo, LV_SIZE_CONTENT);   /// 677
    lv_obj_set_height(ui_CWlogo, LV_SIZE_CONTENT);    /// 369
    lv_obj_set_x(ui_CWlogo, 17);
    lv_obj_set_y(ui_CWlogo, -46);
    lv_obj_set_align(ui_CWlogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CWlogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CWlogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_CWlogo, 300);

    ui_Container11 = lv_obj_create(ui_welcomepage);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_width(ui_Container11, 769);
    lv_obj_set_height(ui_Container11, 21);
    lv_obj_set_x(ui_Container11, 2);
    lv_obj_set_y(ui_Container11, 219);
    lv_obj_set_align(ui_Container11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_waterquallbl1 = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_waterquallbl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_waterquallbl1, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_x(ui_waterquallbl1, -330);
    lv_obj_set_y(ui_waterquallbl1, 4);
    lv_obj_set_align(ui_waterquallbl1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_waterquallbl1, "Water quality:");
    lv_obj_set_style_text_color(ui_waterquallbl1, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_waterquallbl1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_waterqualstat1 = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_waterqualstat1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_waterqualstat1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_waterqualstat1, -214);
    lv_obj_set_y(ui_waterqualstat1, 4);
    lv_obj_set_align(ui_waterqualstat1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_waterqualstat1, "EXCELLENT");
    lv_obj_set_style_text_color(ui_waterqualstat1, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_waterqualstat1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wifilbl1 = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_Wifilbl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifilbl1, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_x(ui_Wifilbl1, 248);
    lv_obj_set_y(ui_Wifilbl1, 4);
    lv_obj_set_align(ui_Wifilbl1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Wifilbl1, "WiFi:");
    lv_obj_set_style_text_color(ui_Wifilbl1, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Wifilbl1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wifistat1 = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_Wifistat1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifistat1, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_x(ui_Wifistat1, 338);
    lv_obj_set_y(ui_Wifistat1, 4);
    lv_obj_set_align(ui_Wifistat1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Wifistat1, "CONNECTED");
    lv_obj_set_style_text_color(ui_Wifistat1, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Wifistat1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Startbtn, ui_event_Startbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CWlogo, ui_event_CWlogo, LV_EVENT_ALL, NULL);
    lv_obj_add_flag(ui_CWlogo, LV_OBJ_FLAG_CLICKABLE); //added
    uic_Button1 = ui_Startbtn;

}

void ui_welcomepage_screen_destroy(void)
{
    if(ui_welcomepage) lv_obj_del(ui_welcomepage);

    // NULL screen variables
    ui_welcomepage = NULL;
    ui_waterqualind1 = NULL;
    uic_Button1 = NULL;
    ui_Startbtn = NULL;
    ui_Startlbl = NULL;
    ui_Container1 = NULL;
    ui_waterquallbl = NULL;
    ui_waterqualstat = NULL;
    ui_Wifilbl = NULL;
    ui_Wifistat = NULL;
    ui_waterqualpanel1 = NULL;
    ui_CWlogo = NULL;
    ui_Container11 = NULL;
    ui_waterquallbl1 = NULL;
    ui_waterqualstat1 = NULL;
    ui_Wifilbl1 = NULL;
    ui_Wifistat1 = NULL;

}
